// SPDX-License-Identifier: MIT OR Apache-2.0

package ironwood.compiler.doc;

import ironwood.compiler.ast.ClassDeclaration;
import ironwood.compiler.ast.InterfaceDeclaration;
import ironwood.compiler.ast.TypeReference;
import ironwood.compiler.diagnostic.Diagnostic;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.stream.Collectors;

final class MarkdownDoclet {
    static final String GENERATED = "<!-- Generated by IronDocs. Do not edit. -->\n";
    private final List<DocModel.Type> types;
    private final IronDocOptions options;
    private final List<Diagnostic> diagnostics;
    private final Map<String, DocModel.Type> byName;

    MarkdownDoclet(List<DocModel.Type> types, IronDocOptions options, List<Diagnostic> diagnostics) {
        this.types = List.copyOf(types);
        this.options = options;
        this.diagnostics = diagnostics;
        this.byName = types.stream().collect(Collectors.toMap(DocModel.Type::qualifiedName, type -> type));
    }

    Map<Path, String> render() {
        Map<Path, String> pages = new TreeMap<>();
        pages.put(Path.of("assets/irondocs.svg"), GENERATED + banner());
        for (var type : types) {
            if (type.path().equals(Path.of("README.md"))) {
                diagnostics.add(Diagnostic.error(type.unit().source(), type.declaration().span(),
                        "type page collides with the IronDocs index: " + type.qualifiedName()));
            }
        }
        if (!diagnostics.isEmpty()) return pages;
        Map<String, List<DocModel.Type>> packages = new TreeMap<>();
        for (var type : types) packages.computeIfAbsent(type.unit().packageName(), unused -> new ArrayList<>()).add(type);
        StringBuilder index = page(Path.of("README.md"));
        index.append("# ").append(DocComment.literal(options.title)).append("\n\n")
                .append("**API reference** · ").append(types.size()).append(" documented type")
                .append(types.size() == 1 ? "" : "s").append(" · ").append(packages.size()).append(" package")
                .append(packages.size() == 1 ? "" : "s").append("\n\n")
                .append("Browse packages below, then open a type for its declaration, examples, and member reference.\n\n")
                .append("## Packages\n\n| Package | Types |\n| --- | ---: |\n");
        for (var entry : packages.entrySet()) {
            String packageName = entry.getKey().isEmpty() ? "Unnamed package" : entry.getKey();
            Path packagePath = packagePath(entry.getKey());
            index.append("| [").append(DocComment.code(packageName)).append("](").append(url(packagePath))
                    .append(") | ").append(entry.getValue().size()).append(" |\n");
            StringBuilder pkg = page(packagePath);
            pkg.append("[All packages](").append(relative(packagePath, Path.of("README.md"))).append(")\n\n")
                    .append("# ").append(DocComment.code(packageName)).append("\n\n")
                    .append("**Package reference**\n\n| Type | Kind | Description |\n| --- | --- | --- |\n");
            for (var type : entry.getValue()) {
                try {
                    pkg.append("| [").append(DocComment.code(type.localName())).append("](")
                            .append(relative(packagePath, type.path())).append(") | ").append(type.kind())
                            .append(" | ").append(cell(summary(type, type.comment(), packagePath))).append(" |\n");
                    pages.put(type.path(), renderType(type));
                } catch (IllegalArgumentException exception) {
                    diagnostics.add(Diagnostic.error(type.unit().source(), type.declaration().span(), exception.getMessage()));
                }
            }
            pages.put(packagePath, pkg.append(FOOTER).toString());
        }
        index.append("\n## Types\n\n| Type | Package | Description |\n| --- | --- | --- |\n");
        for (var type : types) {
            try {
                index.append("| [").append(DocComment.code(type.localName())).append("](").append(url(type.path()))
                        .append(") | ").append(DocComment.code(type.unit().packageName())).append(" | ")
                        .append(cell(summary(type, type.comment(), Path.of("README.md")))).append(" |\n");
            } catch (IllegalArgumentException exception) {
                // The type-page pass already reported this comment with its source span.
            }
        }
        pages.put(Path.of("README.md"), index.append(FOOTER).toString());
        return pages;
    }

    private String renderType(DocModel.Type type) {
        Path page = type.path();
        StringBuilder out = page(page);
        out.append("[All packages](").append(relative(page, Path.of("README.md"))).append(") / [")
                .append(DocComment.code(type.unit().packageName().isEmpty() ? "Unnamed package" : type.unit().packageName()))
                .append("](").append(relative(page, packagePath(type.unit().packageName()))).append(")\n\n")
                .append("# ").append(type.localName()).append("\n\n")
                .append("**").append(type.kind().substring(0, 1).toUpperCase(java.util.Locale.ROOT))
                .append(type.kind().substring(1)).append("** · ").append(DocComment.code(type.qualifiedName())).append("\n\n")
                .append(DocComment.fence(type.signature())).append('\n');
        if (type.declaration() instanceof ClassDeclaration declaration) {
            appendSupertypes(out, type, "Extends", declaration.superclass().stream().toList());
            appendSupertypes(out, type, "Implements", declaration.implementedInterfaces());
        } else if (type.declaration() instanceof InterfaceDeclaration declaration) {
            appendSupertypes(out, type, "Extends", declaration.extendedInterfaces());
        }
        appendComment(out, type, type.comment(), page);
        List<DocModel.Type> nested = types.stream().filter(candidate -> candidate.unit() == type.unit()
                && type.declaration().memberTypes().contains(candidate.declaration())).toList();
        if (!nested.isEmpty()) {
            out.append("\n## Nested types\n\n");
            for (var child : nested) out.append("- [").append(DocComment.code(child.localName())).append("](")
                    .append(relative(page, child.path())).append(")\n");
        }
        Map<String, List<DocModel.Member>> sections = new LinkedHashMap<>();
        for (String section : List.of("Enum constants", "Fields", "Constructors", "Methods")) {
            var members = type.members().stream().filter(member -> member.section().equals(section)).toList();
            if (!members.isEmpty()) sections.put(section, members);
        }
        if (!sections.isEmpty()) {
            out.append("\n## Member summary\n\n");
            out.append(sections.keySet().stream().map(section -> "[" + section + "](#" + slug(section) + ")")
                    .collect(Collectors.joining(" · "))).append("\n\n");
            out.append("| Member | Description |\n| --- | --- |\n");
            for (var member : type.members()) {
                out.append("| [").append(DocComment.code(member.reference())).append("](#").append(member.anchor())
                        .append(") | ").append(cell(summary(type, member.comment(), page))).append(" |\n");
            }
        }
        for (var section : sections.entrySet()) {
            out.append("\n## ").append(section.getKey()).append("\n");
            for (var member : section.getValue()) {
                out.append("\n<a name=\"").append(member.anchor()).append("\"></a>\n\n### ")
                        .append(DocComment.code(member.reference())).append("\n\n")
                        .append(DocComment.fence(member.signature())).append('\n');
                try {
                    appendComment(out, type, member.comment(), page);
                } catch (IllegalArgumentException exception) {
                    diagnostics.add(Diagnostic.error(type.unit().source(), member.span(), exception.getMessage()));
                }
                out.append("\n[Back to member summary](#member-summary)\n");
            }
        }
        return out.append(FOOTER).toString();
    }

    private void appendSupertypes(StringBuilder out, DocModel.Type type, String label, List<TypeReference> parents) {
        if (parents.isEmpty()) return;
        out.append("**").append(label).append(":** ")
                .append(parents.stream().map(parent -> link(type, parent.name() + " " + parent.displayName(), true, type.path()))
                        .collect(Collectors.joining(", ")))
                .append("\n\n");
    }

    private void appendComment(StringBuilder out, DocModel.Type type, DocComment comment, Path page) {
        if (!comment.description().isEmpty()) out.append(text(type, comment.description(), page)).append("\n\n");
        List<DocComment.Tag> params = comment.tags().stream().filter(tag -> tag.name().equals("param")).toList();
        if (!params.isEmpty()) {
            out.append("**Parameters**\n\n| Name | Description |\n| --- | --- |\n");
            for (var tag : params) out.append("| ").append(DocComment.code(DocComment.head(tag.value())))
                    .append(" | ").append(cell(text(type, DocComment.tail(tag.value()), page))).append(" |\n");
            out.append('\n');
        }
        List<DocComment.Tag> thrown = comment.tags().stream()
                .filter(tag -> tag.name().equals("throws") || tag.name().equals("exception"))
                .filter(tag -> !allocationFailure(type, DocComment.head(tag.value()))).toList();
        if (!thrown.isEmpty()) {
            out.append("**Throws**\n\n| Exception | Condition |\n| --- | --- |\n");
            for (var tag : thrown) out.append("| ").append(link(type, DocComment.head(tag.value()), true, page))
                    .append(" | ").append(cell(text(type, DocComment.tail(tag.value()), page))).append(" |\n");
            out.append('\n');
        }
        for (var tag : comment.tags()) {
            if (tag.name().equals("param") || tag.name().equals("throws") || tag.name().equals("exception")) continue;
            if (tag.name().equals("author") && !options.author || tag.name().equals("version") && !options.documentVersion) continue;
            String content = tag.name().equals("see") ? (tag.value().startsWith("\"")
                    ? text(type, tag.value(), page) : link(type, tag.value(), true, page)) : text(type, tag.value(), page);
            if (tag.name().equals("deprecated")) {
                out.append("> [!WARNING]\n> **Deprecated.** ").append(content.replace("\n", "\n> ")).append("\n\n");
            } else {
                String label = switch (tag.name()) {
                    case "return" -> "Returns";
                    case "see" -> "See also";
                    case "since" -> "Since";
                    case "author" -> "Author";
                    case "version" -> "Version";
                    default -> throw new IllegalArgumentException("unsupported IronDocs tag @" + tag.name());
                };
                out.append("**").append(label).append("**\n\n").append(content).append("\n\n");
            }
        }
    }

    private String text(DocModel.Type type, String value, Path page) {
        return DocComment.render(value, (reference, code) -> link(type, reference, code, page));
    }

    private boolean allocationFailure(DocModel.Type context, String name) {
        if (name.equals("ironwood.lang.OutOfMemoryError")) return true;
        DocModel.Type target = resolve(context, name);
        if (target != null) return target.qualifiedName().equals("ironwood.lang.OutOfMemoryError");
        if (!name.equals("OutOfMemoryError")) return false;
        // Partial documentation can omit the implicit language type. Honor an
        // explicit import of a different type even when its page is not selected.
        for (var imported : context.unit().imports()) {
            if (!imported.staticImport() && !imported.wildcard() && imported.importedSimpleName().equals(name)) {
                return imported.name().equals("ironwood.lang.OutOfMemoryError");
            }
        }
        return true;
    }

    private String summary(DocModel.Type type, DocComment comment, Path page) {
        String rendered = text(type, DocComment.firstSentence(comment.description()), page);
        return rendered.isBlank() ? "" : rendered;
    }

    private String link(DocModel.Type current, String value, boolean code, Path page) {
        int end = 0;
        int parentheses = 0;
        while (end < value.length()) {
            char c = value.charAt(end);
            if (c == '(') parentheses++;
            else if (c == ')') parentheses--;
            if (Character.isWhitespace(c) && parentheses == 0) break;
            end++;
        }
        String reference = value.substring(0, end).replaceAll("\\s+", "");
        String label = value.substring(end).strip();
        if (reference.isEmpty()) throw new IllegalArgumentException("empty IronDocs link");
        if (label.isEmpty()) label = reference.startsWith("#") ? reference.substring(1) : reference;
        String display = code ? DocComment.code(label) : DocComment.literal(label);
        int hash = reference.indexOf('#');
        String owner = hash < 0 ? reference : reference.substring(0, hash);
        DocModel.Type target = owner.isEmpty() ? current : resolve(current, owner);
        // References outside this generation retain readable labels instead of broken URLs.
        if (target == null) return display;
        String anchor = "";
        if (hash >= 0) {
            String memberReference = reference.substring(hash + 1);
            var matches = target.members().stream().filter(member -> member.reference().equals(memberReference)
                    || (!memberReference.contains("(") && member.name().equals(memberReference))
                    || memberReference.contains("(") && canonical(target, member.reference()).equals(canonical(current, memberReference)))
                    .toList();
            if (matches.size() != 1) throw new IllegalArgumentException("unresolved or ambiguous IronDocs member link: " + reference);
            anchor = "#" + matches.getFirst().anchor();
        }
        String destination = page.equals(target.path()) && !anchor.isEmpty() ? anchor : relative(page, target.path()) + anchor;
        return "[" + display + "](" + destination + ")";
    }

    private String canonical(DocModel.Type context, String reference) {
        // Javadoc member references use raw parameter type names for generics.
        StringBuilder erased = new StringBuilder();
        int depth = 0;
        for (char c : reference.toCharArray()) {
            if (c == '<') depth++;
            else if (c == '>') depth--;
            else if (depth == 0) erased.append(c);
        }
        reference = erased.toString();
        var matcher = java.util.regex.Pattern.compile("[A-Za-z_$][A-Za-z0-9_$.]*").matcher(reference);
        StringBuilder result = new StringBuilder();
        int last = 0;
        while (matcher.find()) {
            result.append(reference, last, matcher.start());
            var type = resolve(context, matcher.group());
            result.append(type == null ? matcher.group() : type.qualifiedName());
            last = matcher.end();
        }
        return result.append(reference.substring(last)).toString();
    }

    private DocModel.Type resolve(DocModel.Type current, String name) {
        if (byName.containsKey(name)) return byName.get(name);
        String local = current.unit().packageName().isEmpty() ? name : current.unit().packageName() + "." + name;
        if (byName.containsKey(local)) return byName.get(local);
        String nested = current.qualifiedName() + "." + name;
        if (byName.containsKey(nested)) return byName.get(nested);
        for (var imported : current.unit().imports()) {
            if (imported.staticImport()) continue;
            if (!imported.wildcard() && imported.importedSimpleName().equals(name)) return byName.get(imported.name());
        }
        List<DocModel.Type> candidates = new ArrayList<>();
        for (var imported : current.unit().imports()) {
            if (imported.wildcard() && !imported.staticImport()) {
                var candidate = byName.get(imported.name() + "." + name);
                if (candidate != null && !candidates.contains(candidate)) candidates.add(candidate);
            }
        }
        var implicit = byName.get("ironwood.lang." + name);
        if (implicit != null && !candidates.contains(implicit)) candidates.add(implicit);
        return candidates.size() == 1 ? candidates.getFirst() : null;
    }

    private StringBuilder page(Path path) {
        StringBuilder result = new StringBuilder(GENERATED).append('\n').append("![IronDocs API reference](")
                .append(relative(path, Path.of("assets/irondocs.svg"))).append(")\n\n");
        if (!options.apiVersion.isEmpty()) {
            result.append("**Version ").append(DocComment.literal(options.apiVersion)).append("**\n\n");
        }
        return result;
    }

    private String banner() {
        String version = options.apiVersion.isEmpty() ? "API reference" : "Version " + options.apiVersion;
        return BANNER.formatted(xml(options.title), xml(version), xml(options.title), xml(version));
    }

    private static String xml(String text) {
        return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                .replace("\"", "&quot;").replace("'", "&apos;");
    }

    private static Path packagePath(String name) {
        return Path.of(name.replace('.', '/'), "package-summary.md");
    }

    private static String cell(String text) {
        return text.replace("\\|", "|").replace("|", "\\|").replaceAll("\\s*\\R\\s*", " ");
    }

    private static String relative(Path from, Path to) {
        return url((from.getParent() == null ? Path.of("") : from.getParent()).relativize(to));
    }

    private static String url(Path path) {
        return path.toString().replace(java.io.File.separatorChar, '/').replace("%", "%25")
                .replace(" ", "%20").replace("#", "%23").replace("?", "%3F");
    }

    private static String slug(String section) {
        return section.toLowerCase(java.util.Locale.ROOT).replace(' ', '-');
    }

    private static final String FOOTER = "\n---\n\nGenerated from Ironwood source comments with **IronDocs**.\n";
    private static final String BANNER = """
            <svg xmlns="http://www.w3.org/2000/svg" width="1200" height="180" viewBox="0 0 1200 180" role="img" aria-labelledby="title desc">
              <title id="title">%s: IronDocs</title>
              <desc id="desc">IronDocs API reference. %s.</desc>
              <defs>
                <linearGradient id="bg" x2="1" y2="1">
                  <stop stop-color="#102a35"/><stop offset="1" stop-color="#123d38"/>
                </linearGradient>
                <linearGradient id="accent"><stop stop-color="#5eead4"/><stop offset="1" stop-color="#a3e635"/></linearGradient>
              </defs>
              <rect width="1200" height="180" rx="18" fill="url(#bg)"/>
              <path d="M940 0 760 180M1080 0 900 180M1220 0 1040 180" stroke="#5eead4" stroke-opacity=".10" stroke-width="48"/>
              <rect x="36" y="36" width="5" height="108" rx="2" fill="url(#accent)"/>
              <text x="62" y="65" fill="#99c7c4" font-family="system-ui,sans-serif" font-size="14" letter-spacing="3">IRONDOCS / API REFERENCE</text>
              <text x="60" y="116" fill="#f0fdfa" font-family="system-ui,sans-serif" font-size="46" font-weight="700">%s</text>
              <text x="62" y="145" fill="#b6d4d1" font-family="system-ui,sans-serif" font-size="16">%s</text>
              <path d="m1070 55-30 35 30 35m45-70 30 35-30 35" fill="none" stroke="url(#accent)" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
            """;
}
