// SPDX-License-Identifier: MIT OR Apache-2.0

package ironwood.compiler;

import java.lang.reflect.ParameterizedType;
import java.lang.reflect.RecordComponent;
import java.lang.reflect.Type;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.stream.Stream;

/**
 * Reproducible generator for the shared IR variant inventory
 * ({@code compiler/src/main/ironwood/ironwood/compiler/port/IrModel.iron}).
 * It reads the Java IR model by reflection, independently of any dispatch
 * arm, and emits ordinary Ironwood source: every record with its sealed root,
 * its components in declaration order and the components the reflective
 * walkers (ClosedWorldPruner.scanRecord, SemanticAnalyzer.collectArrayTypes)
 * follow, plus every IR enum with its constants. The checked-in file is
 * regenerated by running this class's {@code main} from the repository root;
 * native builds only compile the generated source.
 */
final class IrModelInventory {
    static final Path TARGET = Path.of("compiler/src/main/ironwood/ironwood/compiler/port/IrModel.iron");
    private static final Path MODEL = Path.of("compiler/src/main/java/ironwood/compiler/ir");
    private static final String PACKAGE = "ironwood.compiler.ir.";
    private static final List<String> ROOTS = List.of("IrInstruction", "IrTerminator", "IrOperand");

    private IrModelInventory() { }

    public static void main(String[] args) throws Exception {
        Files.writeString(TARGET, generate(), StandardCharsets.UTF_8);
    }

    /** Every top-level declaration of the IR package and its nested types, in name order. */
    static List<Class<?>> declarations() throws Exception {
        List<Class<?>> result = new ArrayList<>();
        try (Stream<Path> files = Files.list(MODEL)) {
            for (Path file : files.filter(path -> path.toString().endsWith(".java")).sorted().toList()) {
                String name = file.getFileName().toString().replace(".java", "");
                Class<?> type = Class.forName(PACKAGE + name);
                result.add(type);
                Arrays.stream(type.getDeclaredClasses())
                        .sorted((left, right) -> left.getName().compareTo(right.getName()))
                        .forEach(result::add);
            }
        }
        return result;
    }

    static String generate() throws Exception {
        List<Class<?>> records = new ArrayList<>();
        List<Class<?>> enums = new ArrayList<>();
        for (Class<?> type : declarations()) {
            if (type.isRecord()) records.add(type);
            else if (type.isEnum()) enums.add(type);
        }
        StringBuilder out = new StringBuilder();
        out.append("""
                // SPDX-License-Identifier: MIT OR Apache-2.0
                // Generated by compiler/src/test/java/ironwood/compiler/IrModelInventory.java
                // from the Java IR model in compiler/src/main/java/ironwood/compiler/ir. Do not
                // edit: regenerate it, and the test 'IR model inventory matches the Java model'
                // fails while this file and the Java model disagree.

                package ironwood.compiler.port;

                /**
                 * The shared, independent IR variant inventory (D265). Every Java IR record
                 * and enum is listed, derived from the model declarations rather than from
                 * any dispatch arm. Each function is an exhaustive switch without a default,
                 * so a record or enum added here without a treatment, or a deleted treatment,
                 * fails compilation. Consumers that dispatch on IR variants use the same
                 * pattern: the S2 walkers must follow exactly {@link #walked(Record)}, and the
                 * pilot admission functions in {@link OperationVariants} keep their own lists.
                 * Names keep the Java binary name in upper snake case; a nested type's
                 * {@code $} becomes a double underscore.
                 */
                public final class IrModel {

                    private IrModel() {

                    }

                    /** The sealed IR roots; NONE for records outside them. */
                    public enum Root {
                        INSTRUCTION, TERMINATOR, OPERAND, NONE
                    }

                """);
        out.append("    /** Every IR record, in source-name order. */\n    public enum Record {\n");
        appendConstants(out, records.stream().map(IrModelInventory::constant).toList());
        out.append("    }\n\n");
        out.append("    /** Every IR enum, top-level and nested, in source-name order. */\n    public enum Enumeration {\n");
        appendConstants(out, enums.stream().map(IrModelInventory::constant).toList());
        out.append("    }\n\n");
        out.append("    /** @return the sealed root the record implements */\n");
        out.append("    public static Root root(Record record) {\n\n        return switch (record) {\n");
        for (Class<?> record : records) {
            out.append("            case ").append(constant(record)).append(" -> Root.").append(root(record)).append(";\n");
        }
        out.append("        };\n    }\n\n");
        out.append("    /** @return the Java simple name, as {@code getClass().getSimpleName()} renders it in diagnostics */\n");
        out.append("    public static String javaName(Record record) {\n\n        return switch (record) {\n");
        for (Class<?> record : records) {
            out.append("            case ").append(constant(record)).append(" -> \"").append(record.getSimpleName())
                    .append("\";\n");
        }
        out.append("        };\n    }\n\n");
        out.append("    /** @return the record's components in declaration order, as name:JavaType */\n");
        out.append("    public static String components(Record record) {\n\n        return switch (record) {\n");
        for (Class<?> record : records) {
            List<String> parts = new ArrayList<>();
            for (RecordComponent component : record.getRecordComponents()) {
                parts.add(component.getName() + ":" + render(component.getGenericType()));
            }
            out.append("            case ").append(constant(record)).append(" -> \"").append(String.join(",", parts))
                    .append("\";\n");
        }
        out.append("        };\n    }\n\n");
        out.append("""
                    /**
                     * @return the components the reflective IR walkers follow: IR types,
                     *     operands, string constants, dispatch slots, enum constants, fields,
                     *     static fields and nested IR records, directly or through Optional
                     *     and List/Set; never maps, text, primitives, enums or source spans
                     */
                """);
        out.append("    public static String walked(Record record) {\n\n        return switch (record) {\n");
        for (Class<?> record : records) {
            List<String> parts = new ArrayList<>();
            for (RecordComponent component : record.getRecordComponents()) {
                if (followed(component.getGenericType())) parts.add(component.getName());
            }
            out.append("            case ").append(constant(record)).append(" -> \"").append(String.join(",", parts))
                    .append("\";\n");
        }
        out.append("        };\n    }\n\n");
        out.append("    /** @return the enum's constants in declaration order */\n");
        out.append("    public static String constants(Enumeration enumeration) {\n\n        return switch (enumeration) {\n");
        for (Class<?> type : enums) {
            List<String> names = Arrays.stream(type.getEnumConstants()).map(value -> ((Enum<?>) value).name()).toList();
            out.append("            case ").append(constant(type)).append(" -> \"").append(String.join(",", names))
                    .append("\";\n");
        }
        out.append("        };\n    }\n}\n");
        return out.toString();
    }

    private static void appendConstants(StringBuilder out, List<String> constants) {
        StringBuilder line = new StringBuilder("        ");
        for (int index = 0; index < constants.size(); index++) {
            String item = constants.get(index) + (index + 1 < constants.size() ? "," : "");
            if (line.length() + item.length() + 1 > 100) {
                out.append(line.toString().stripTrailing()).append('\n');
                line = new StringBuilder("        ");
            }
            line.append(item).append(' ');
        }
        out.append(line.toString().stripTrailing()).append('\n');
    }

    /** IrType$Kind becomes IR_TYPE__KIND; IrTypeKind becomes IR_TYPE_KIND. */
    static String constant(Class<?> type) {
        String binary = type.getName().substring(PACKAGE.length());
        StringBuilder out = new StringBuilder();
        for (int index = 0; index < binary.length(); index++) {
            char character = binary.charAt(index);
            if (character == '$') {
                out.append("__");
            } else {
                if (Character.isUpperCase(character) && index > 0 && binary.charAt(index - 1) != '$') out.append('_');
                out.append(Character.toUpperCase(character));
            }
        }
        return out.toString();
    }

    private static String root(Class<?> record) {
        List<String> roots = new ArrayList<>();
        for (Class<?> implemented : record.getInterfaces()) {
            if (ROOTS.contains(implemented.getSimpleName())) roots.add(implemented.getSimpleName());
        }
        if (roots.size() > 1) throw new IllegalStateException(record + " implements several IR roots");
        if (roots.isEmpty()) return "NONE";
        return switch (roots.getFirst()) {
            case "IrInstruction" -> "INSTRUCTION";
            case "IrTerminator" -> "TERMINATOR";
            default -> "OPERAND";
        };
    }

    private static String render(Type type) {
        return type.getTypeName().replace("java.util.", "").replace("java.lang.", "")
                .replace("ironwood.compiler.source.", "").replace(PACKAGE, "").replace('$', '.');
    }

    /** Mirrors ClosedWorldPruner.scanRecord's descent: IR-package records, Optional and Iterable. */
    private static boolean followed(Type type) {
        if (type instanceof ParameterizedType parameterized) {
            Class<?> raw = (Class<?>) parameterized.getRawType();
            if (raw == Optional.class || Iterable.class.isAssignableFrom(raw)) {
                return followed(parameterized.getActualTypeArguments()[0]);
            }
            return false;
        }
        if (!(type instanceof Class<?> raw)) return false;
        if (raw.isInterface() && ROOTS.contains(raw.getSimpleName())) return true;
        return raw.isRecord() && raw.getName().startsWith(PACKAGE);
    }
}
