// SPDX-License-Identifier: MIT OR Apache-2.0

import java.util.function.IntPredicate;

/**
 * Generates compiler/src/main/ironwood/ironwood/compiler/port/JavaIdentifiers.iron
 * from Java 21's Character.isJavaIdentifierStart(int) and
 * isJavaIdentifierPart(int), observed for every code point (Unicode 15.0
 * character data as JDK 21 reports it). Run it with JDK 21 and compare its
 * output with the checked-in file; the test `M5.4 Java identifier-part table
 * regenerates from JDK 21` fails when they differ. M5.4 generated the part
 * ranges; M6.1 added the start ranges.
 * Usage: java JavaIdentifierTable.java > JavaIdentifiers.iron
 */
public final class JavaIdentifierTable {
    private JavaIdentifierTable() { }

    public static void main(String[] args) {
        int[] startCount = new int[1];
        int[] partCount = new int[1];
        String start = ranges(Character::isJavaIdentifierStart, startCount);
        String part = ranges(Character::isJavaIdentifierPart, partCount);
        System.out.print("""
                // SPDX-License-Identifier: MIT OR Apache-2.0

                package ironwood.compiler.port;

                /**
                 * Java 21's {@code Character.isJavaIdentifierStart} and
                 * {@code isJavaIdentifierPart} for the compiler's documentation tag scan (B7,
                 * S6) and the Bridge name validator {@link JavaNames} (S7). Starts are
                 * letters, letter numbers, currency symbols and connecting punctuation; parts
                 * add digits, combining marks and identifier-ignorable characters, as JDK 21
                 * reports them for Unicode 15.0. The ranges are generated by
                 * docs/self-hosting/m5/doc-evidence/JavaIdentifierTable.java from the JDK's
                 * observed answer for every code point; they are Unicode character data, whose
                 * notice is LICENSES/Unicode-15.0.txt. Do not edit them by hand: regenerate and
                 * compare.
                 *
                 * <p>A {@code char} is tested as the code point of the same value, as Java's
                 * char overload does, so a surrogate unit is never an identifier start or part.
                 * Lookups allocate nothing.
                 */
                public final class JavaIdentifiers {

                    // %d inclusive [first, last] ranges, ascending.
                    private static final int[] START = {%s
                    };

                    // %d inclusive [first, last] ranges, ascending.
                    private static final int[] PART = {%s
                    };

                    private JavaIdentifiers() {

                    }

                    /** @return whether Java 21's {@code Character.isJavaIdentifierStart(int)} accepts the code point */
                    public static boolean isJavaIdentifierStart(int codePoint) {

                        if (codePoint < 0x80) {
                            return codePoint >= 'a' && codePoint <= 'z' || codePoint >= 'A' && codePoint <= 'Z'
                                    || codePoint == '_' || codePoint == '$';
                        }
                        return contains(START, codePoint);
                    }

                    /** @return whether Java 21's {@code Character.isJavaIdentifierPart(char)} accepts the unit */
                    public static boolean isJavaIdentifierPart(char unit) {

                        return isJavaIdentifierPart((int) unit);
                    }

                    /** @return whether Java 21's {@code Character.isJavaIdentifierPart(int)} accepts the code point */
                    public static boolean isJavaIdentifierPart(int codePoint) {

                        if (codePoint < 0x80) {
                            return codePoint >= 'a' && codePoint <= 'z' || codePoint >= 'A' && codePoint <= 'Z'
                                    || codePoint >= '0' && codePoint <= '9' || codePoint == '_' || codePoint == '$'
                                    || codePoint <= 8 || codePoint >= 0x0E && codePoint <= 0x1B || codePoint == 0x7F;
                        }
                        return contains(PART, codePoint);
                    }

                    // Binary search over inclusive [first, last] pairs.
                    private static boolean contains(int[] ranges, int codePoint) {

                        int low = 0;
                        int high = ranges.length / 2 - 1;
                        while (low <= high) {
                            int middle = (low + high) >>> 1;
                            if (codePoint < ranges[middle * 2]) {
                                high = middle - 1;
                            } else if (codePoint > ranges[middle * 2 + 1]) {
                                low = middle + 1;
                            } else {
                                return true;
                            }
                        }
                        return false;
                    }
                }
                """.formatted(startCount[0], start, partCount[0], part));
    }

    // The accepted code points as inclusive ranges, six per line.
    private static String ranges(IntPredicate accepted, int[] count) {
        StringBuilder ranges = new StringBuilder();
        int code = 0;
        while (code <= Character.MAX_CODE_POINT) {
            if (!accepted.test(code)) {
                code++;
                continue;
            }
            int start = code;
            while (code <= Character.MAX_CODE_POINT && accepted.test(code)) code++;
            if (count[0] % 6 == 0) ranges.append("\n       ");
            ranges.append(String.format(" 0x%06X, 0x%06X,", start, code - 1));
            count[0]++;
        }
        ranges.setLength(ranges.length() - 1);
        return ranges.toString();
    }
}
