#!/usr/bin/env bash
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Generates the native compiler's build identity (D269): Ironwood source that
# replaces the VERSION resource CompilerVersion reads. The version follows
# scripts/build.sh exactly (IRONWOOD_VERSION when set, otherwise VERSION with
# all whitespace removed, then the same validation and messages), so the
# value equals CompilerVersion.current() for a jar built from the same
# inputs. The output depends only on that version and is byte-identical
# across runs; no Java tool is involved.
#
# Usage: build-identity.sh OUTPUT [PROJECT_ROOT]

set -euo pipefail

output=${1:?usage: build-identity.sh OUTPUT [PROJECT_ROOT]}
root=${2:-$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)}
version=${IRONWOOD_VERSION:-}
if [[ -z "$version" ]]; then
    if [[ ! -f "$root/VERSION" ]]; then
        echo "error: missing compiler version file: $root/VERSION" >&2
        exit 1
    fi
    version=$(tr -d '[:space:]' < "$root/VERSION")
fi
if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z.-]+)?$ ]]; then
    echo "error: invalid compiler version '$version'" >&2
    exit 1
fi

# The validated version has no quote, backslash or line break to escape.
cat > "$output" <<EOF
// SPDX-License-Identifier: MIT OR Apache-2.0
// Generated by scripts/self-hosting/build-identity.sh; do not edit.

package ironwood.compiler.port;

/** The build identity that scripts/build.sh embeds as the VERSION resource. */
public final class BuildIdentity {

    private BuildIdentity() {

    }

    /** CompilerVersion.current(): the validated compiler version. */
    public static String version() {

        return "$version";
    }
}
EOF
