#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Generate scripts/self-hosting/native/FrontendLiterals.iron for the M2.1 census.

Usage: generate-frontend-literals.py OUTPUT PORT_SOURCES...

Emit every string literal of the port sources, and every constant-folded run
of adjacent literal concatenations, as Ironwood literals that keep canonical
identity. The census pre-marks them, so literal diagnostic messages and the
end-of-file lexeme count as no allocation. Over-inclusion is harmless: a
runtime-created string is never identical to a literal."""
import sys



def tokens(text):
    """Yield ('string', raw) and ('plus', '+') and ('other', '') tokens, skipping comments and char literals."""
    i, n = 0, len(text)
    while i < n:
        c = text[i]
        if text.startswith('//', i):
            i = text.find('\n', i)
            i = n if i < 0 else i
        elif text.startswith('/*', i):
            i = text.index('*/', i + 2) + 2
        elif text.startswith('"""', i):
            i = text.index('"""', i + 3) + 3
            yield ('other', '')
        elif c == '"':
            j = i + 1
            while text[j] != '"':
                j += 2 if text[j] == '\\' else 1
            yield ('string', text[i:j + 1])
            i = j + 1
        elif c == "'":
            j = i + 1
            while text[j] != "'":
                j += 2 if text[j] == '\\' else 1
            i = j + 1
            yield ('other', '')
        elif c == '+':
            yield ('plus', '+')
            i += 1
        elif c.isspace():
            i += 1
        else:
            yield ('other', '')
            i += 1


def literal_runs(text):
    runs = set()
    run = []
    previous = None
    for kind, value in tokens(text):
        if kind == 'string':
            if previous == 'plus' and run:
                run.append(value)
            else:
                run = [value]
            for length in range(1, len(run) + 1):
                runs.add(' + '.join(run[:length]))
            runs.add(value)
        elif kind == 'other':
            run = []
        previous = kind
    return sorted(runs)


def main():
    out, sources = sys.argv[1], sys.argv[2:]
    runs = set()
    for path in sources:
        runs.update(literal_runs(open(path, encoding='utf-8').read()))
    lines = ['// SPDX-License-Identifier: MIT OR Apache-2.0', '',
             'import ironwood.ds.IdentityHashSet;', '',
             '/**',
             ' * Generated by the M2 census tooling from the port sources: every string',
             ' * literal and constant-folded literal concatenation they contain. Literals',
             ' * keep one canonical identity, so marking these objects lets the census',
             ' * count only strings created at run time.',
             ' */',
             'final class FrontendLiterals {', '',
             '    private FrontendLiterals() {', '',
             '    }', '',
             '    static void mark(IdentityHashSet<Object> seen) {', '']
    for run in sorted(runs):
        lines.append('        seen.add(%s);' % run)
    lines += ['    }', '}']
    open(out, 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
    print(len(runs), 'literal forms')


if __name__ == '__main__':
    main()
