// SPDX-License-Identifier: MIT OR Apache-2.0

import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.text.BreakIterator;
import java.util.Locale;
import java.util.StringJoiner;
import java.util.function.IntPredicate;

/** Extracts Unicode 15.0 Character properties and fixed en_US casing from the pinned JDK. */
public final class GenerateCaseData {
    private static final Class<?> WORDS;

    static {
        try {
            WORDS = Class.forName("sun.text.RuleBasedBreakIterator");
        } catch (ClassNotFoundException exception) {
            throw new ExceptionInInitializerError(exception);
        }
    }

    private static Object field(Object object, String name) throws Exception {
        Field member = WORDS.getDeclaredField(name);
        member.setAccessible(true);
        return member.get(object);
    }

    private static void shorts(StringBuilder output, String name, short[] values) {
        output.append("static const int16_t ").append(name).append("[] = {\n");
        for (int i = 0; i < values.length; i++) {
            output.append(values[i]).append(',').append(i % 24 == 23 || i + 1 == values.length ? '\n' : ' ');
        }
        output.append("\n};\n");
    }

    private static void booleans(StringBuilder output, String name, boolean[] values) {
        output.append("static const unsigned char ").append(name).append("[] = {\n");
        for (boolean value : values) output.append(value ? "1," : "0,");
        output.append("\n};\n");
    }

    private static String units(String text) {
        if (text.length() > 3) throw new IllegalArgumentException("case mapping exceeds bounded storage");
        StringJoiner result = new StringJoiner(",", "{", "}");
        for (int i = 0; i < 3; i++) result.add(Integer.toString(i < text.length() ? text.charAt(i) : 0));
        return result.toString();
    }

    private static void ranges(StringBuilder output, String name, IntPredicate predicate) {
        output.append("static const struct character_range ").append(name).append("[] = {\n");
        int start = -1;
        for (int point = 0; point <= 0x10ffff; point++) {
            if (predicate.test(point)) {
                if (start < 0) start = point;
            } else if (start >= 0) {
                output.append('{').append(start).append(',').append(point - 1).append("},\n");
                start = -1;
            }
        }
        if (start >= 0) output.append('{').append(start).append(",1114111},\n");
        output.append("};\n");
    }

    private static void values(StringBuilder output, String name,
                               java.util.function.IntUnaryOperator operation) {
        output.append("static const struct character_value ").append(name).append("[] = {\n");
        for (int point = 0; point <= 0x10ffff; point++) {
            int value = operation.applyAsInt(point);
            if (value != -1) output.append('{').append(point).append(',').append(value).append("},\n");
        }
        output.append("};\n");
    }

    public static void main(String[] args) throws Exception {
        if (args.length != 3) throw new IllegalArgumentException(
                "usage: GenerateCaseData.java helper.c BreakIteratorRules.java output.h");
        Runtime.Version version = Runtime.version();
        if (!version.version().equals(java.util.List.of(21, 0, 1)) || version.build().orElse(-1) != 12) {
            throw new IllegalArgumentException("requires JDK 21.0.1+12 (Unicode 15.0)");
        }
        String helper = Files.readString(Path.of(args[0]));
        StringBuilder output = new StringBuilder(helper.substring(0, helper.indexOf("#include")));
        String rules = Files.readString(Path.of(args[1]), StandardCharsets.UTF_8);
        String rulesDigest = java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256")
                .digest(rules.getBytes(StandardCharsets.UTF_8)));
        if (!rulesDigest.equals("7b4a1dd9fc02bcc0f7885209ffc4f462467631d2cddfa395f6bc7d6772300aae")) throw new IllegalArgumentException("word-rule source checksum mismatch");
        output.append(rules.substring(0, rules.indexOf("package ")));
        output.append("/* Also derived from OpenJDK: src/java.base/share/classes/sun/text/resources/BreakIteratorRules.java */\n");
        output.append("/* Generated by scripts/GenerateCaseData.java; fixed en_US only.\n")
                .append(" * Unicode 15.0 data notice: LICENSES/Unicode-15.0.txt. */\n");
        Class<?> conditional = Class.forName("java.lang.ConditionalSpecialCasing");
        Method cased = conditional.getDeclaredMethod("isCased", int.class);
        cased.setAccessible(true);
        Method category = WORDS.getDeclaredMethod("lookupCategory", int.class);
        category.setAccessible(true);
        BreakIterator words = BreakIterator.getWordInstance(Locale.US);
        shorts(output, "word_states", (short[]) field(words, "stateTable"));
        shorts(output, "word_backwards", (short[]) field(words, "backwardsStateTable"));
        booleans(output, "word_end", (boolean[]) field(words, "endStates"));
        booleans(output, "word_lookahead", (boolean[]) field(words, "lookaheadStates"));
        output.append("#define WORD_CATEGORIES ").append(field(words, "numCategories")).append('\n');
        output.append("struct case_record { uint32_t point, simple_lower, simple_upper; uint16_t lower[3], upper[3]; unsigned char lower_length, upper_length; };\n")
                .append("static const struct case_record case_records[] = {\n");
        for (int point = 0; point <= 0x10ffff; point++) {
            String original = new String(Character.toChars(point));
            String lower = original.toLowerCase(Locale.US), upper = original.toUpperCase(Locale.US);
            int simpleLower = Character.toLowerCase(point), simpleUpper = Character.toUpperCase(point);
            if (simpleLower != point || simpleUpper != point || !lower.equals(original) || !upper.equals(original)) {
                output.append('{').append(point).append(',').append(simpleLower).append(',').append(simpleUpper)
                        .append(',').append(units(lower)).append(',').append(units(upper))
                        .append(',').append(lower.length()).append(',').append(upper.length()).append("},\n");
            }
        }
        output.append("};\nstruct case_property { uint32_t start; int16_t category; unsigned char cased; };\n")
                .append("static const struct case_property case_properties[] = {\n");
        String previous = "";
        for (int point = 0; point <= 0x10ffff; point++) {
            String properties = category.invoke(words, point) + "," + ((boolean) cased.invoke(null, point) ? 1 : 0);
            if (!properties.equals(previous)) {
                output.append('{').append(point).append(',').append(properties).append("},\n");
                previous = properties;
            }
        }
        output.append("};\n")
                .append("struct character_range { uint32_t start, end; };\n")
                .append("struct character_value { uint32_t point; int32_t value; };\n");
        ranges(output, "character_digit_ranges", Character::isDigit);
        ranges(output, "character_letter_ranges", Character::isLetter);
        ranges(output, "character_upper_ranges", Character::isUpperCase);
        ranges(output, "character_lower_ranges", Character::isLowerCase);
        values(output, "character_digit_values", point -> Character.digit(point, 36));
        values(output, "character_numeric_values", Character::getNumericValue);
        Files.writeString(Path.of(args[2]), output, StandardCharsets.UTF_8);
    }
}
