#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0

"""Maintain the versioned standard-library reference without publishing a release."""

import argparse
import hashlib
import html
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile


GENERATED = "<!-- Generated by IronDocs. Do not edit. -->\n"
VERSION = re.compile(r"(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-[0-9A-Za-z]+(?:[.-][0-9A-Za-z]+)*)?")
INPUTS = ["VERSION", "docs/STDLIB.md", "stdlib/src/main/ironwood", "compiler/src/main/java",
          "bin/irondoc", "scripts/build.sh", "scripts/update-irondocs.sh", "scripts/irondocs.py"]


def git(root, *args):
    return subprocess.run(["git", "-C", str(root), *args], check=True,
                          stdout=subprocess.PIPE, text=True).stdout.strip()


def files(directory):
    if directory.is_symlink():
        raise ValueError(f"refusing symbolic-link directory: {directory}")
    result = {}
    if directory.exists():
        for path in sorted(directory.rglob("*")):
            if path.is_symlink():
                raise ValueError(f"refusing symbolic-link file or directory: {path}")
            if path.is_file():
                result[path.relative_to(directory).as_posix()] = path.read_bytes()
    return result


def source_digest(root):
    digest = hashlib.sha256()
    for name, content in files(root / "stdlib/src/main/ironwood").items():
        if name.endswith(".iron"):
            digest.update(name.encode() + b"\0" + str(len(content)).encode() + b"\0" + content)
    return digest.hexdigest()


def generated_inventory(readme):
    summary = re.search(r"\*\*API reference\*\* · ([0-9]+) documented types? · ([0-9]+) packages?", readme)
    if summary is None:
        raise ValueError("generated IronDocs index has no API inventory")
    packages = dict((name, int(count)) for name, count in re.findall(
        r"^\| \[`([^`]+)`\]\([^)]*package-summary\.md\) \| ([0-9]+) \|$", readme, re.MULTILINE))
    documented = int(summary.group(1))
    package_count = int(summary.group(2))
    if len(packages) != package_count or sum(packages.values()) != documented:
        raise ValueError("generated IronDocs inventory totals are inconsistent")
    return documented, packages


def validate_stdlib_inventory(root, generated_readme):
    text = (root / "docs/STDLIB.md").read_text(encoding="utf-8")
    summary = re.search(
        r"standard library from ([0-9]+)\nsource files?\. IronDocs covers ([0-9]+) public and protected types? across ([0-9]+) packages?:",
        text)
    if summary is None:
        raise ValueError("docs/STDLIB.md has no mechanically checked API inventory")
    actual_source_files = int(summary.group(1))
    actual_documented = int(summary.group(2))
    actual_package_count = int(summary.group(3))
    inventory_block = text.split("This document describes", 1)[0]
    actual_packages = dict((name, int(count)) for name, count in re.findall(
        r"^\| `([^`]+)` \| ([0-9]+) \|", inventory_block, re.MULTILINE))

    expected_source_files = sum(name.endswith(".iron")
                                for name in files(root / "stdlib/src/main/ironwood"))
    expected_documented, expected_packages = generated_inventory(generated_readme)
    differences = []
    if actual_source_files != expected_source_files:
        differences.append(f"source files: expected {expected_source_files}, found {actual_source_files}")
    if actual_documented != expected_documented:
        differences.append(f"documented types: expected {expected_documented}, found {actual_documented}")
    if actual_package_count != len(expected_packages):
        differences.append(f"packages: expected {len(expected_packages)}, found {actual_package_count}")
    if actual_packages != expected_packages:
        differences.append("package rows differ from generated IronDocs")
    if differences:
        raise ValueError("docs/STDLIB.md inventory is out of date (" + "; ".join(differences) + ")")


def package_descriptions(root):
    text = (root / "docs/STDLIB.md").read_text(encoding="utf-8")
    inventory = text.split("This document describes", 1)[0]
    descriptions = {}
    for package, description in re.findall(
            r"^\| `([^`]+)` \| [0-9]+ \| (.+) \|$", inventory, re.MULTILINE):
        descriptions[package] = description
    return descriptions


def add_package_descriptions(root, generated):
    for package, description in package_descriptions(root).items():
        page = generated / package.replace(".", "/") / "package-summary.md"
        if not page.exists():
            continue
        text = page.read_text(encoding="utf-8")
        marker = "**Package reference**\n"
        if marker not in text:
            raise ValueError(f"generated package page has no package reference marker: {page}")
        description = description.rstrip()
        if description[-1] not in ".!?":
            description += "."
        page.write_text(text.replace(marker, marker + "\n" + description + "\n", 1), encoding="utf-8")


def snapshots(api):
    """Only generated version directories may be replaced or retired."""
    versions = {}
    if not api.exists():
        return versions
    for path in api.iterdir():
        if path.is_symlink():
            raise ValueError(f"refusing symbolic-link output: {path}")
        if path.name == "README.md" and path.is_file():
            if not path.read_text(encoding="utf-8").startswith(GENERATED):
                raise ValueError(f"refusing to overwrite non-generated file: {path}")
            continue
        if not path.is_dir() or not VERSION.fullmatch(path.name):
            raise ValueError(f"unexpected file in generated documentation: {path}")
        contents = files(path)
        metadata = json.loads(contents.get("snapshot.json", b"{}"))
        if not isinstance(metadata, dict) or metadata.get("generator") != "IronDocs" or metadata.get("version") != path.name:
            raise ValueError(f"missing IronDocs snapshot metadata: {path}")
        for name, content in contents.items():
            if name != "snapshot.json" and not content.startswith(GENERATED.encode()):
                raise ValueError(f"refusing to overwrite non-generated file: {path / name}")
        versions[path.name] = contents
    return versions


def version_key(version):
    return tuple(map(int, VERSION.fullmatch(version).groups()[:3]))


def validate_status(status):
    if not isinstance(status, str) or not status.strip() or status.splitlines() != [status] or "\0" in status:
        raise ValueError("--status must be non-empty, single-line text")
    return status.strip()


def status_text(version, metadata):
    if "-" in version:
        return "Development (updated in place)"
    if "status" in metadata:
        return validate_status(metadata["status"])
    return "Stable release"


def index_row(version, metadata):
    # Status is plain text, including when it contains Markdown or HTML syntax.
    status = html.escape(status_text(version, metadata), quote=False)
    status = re.sub(r"([\\`*_|\[\]~])", r"\\\1", status)
    return f"| [{version}]({version}/README.md) | {status} |"


def index(versions):
    development = sorted((v for v in versions if "-" in v), key=version_key, reverse=True)
    releases = sorted((v for v in versions if "-" not in v), key=version_key, reverse=True)
    current = (development + releases)[0]
    result = (GENERATED + f"\n![IronDocs API reference]({current}/assets/irondocs.svg)\n\n"
              "# Ironwood Standard Library\n\n"
              "Browse the reference for the version of Ironwood you use. Development documentation "
              "changes with the source; stable release documentation is frozen.\n\n"
              "| Version | Status |\n| --- | --- |\n")
    for version in development + releases:
        metadata = json.loads(versions[version]["snapshot.json"])
        result += index_row(version, metadata) + "\n"
    return result


def update(root, args):
    if sum(bool(getattr(args, name, False)) for name in ("commit", "commitpush", "no_commit", "check")) > 1:
        raise ValueError("choose only one of --commit, --commitpush, --no-commit, or --check")
    push = getattr(args, "commitpush", False)
    commit = getattr(args, "commit", False) or push
    if Path(git(root, "rev-parse", "--show-toplevel")).resolve() != root:
        raise ValueError("run the script from an Ironwood Git checkout")
    version = (root / "VERSION").read_text(encoding="utf-8").strip()
    if not VERSION.fullmatch(version):
        raise ValueError(f"invalid VERSION: {version!r}")
    stable = "-" not in version
    if args.release and not stable:
        raise ValueError("--release requires a stable VERSION, such as 0.1.3")
    if stable and not (args.release or args.check):
        raise ValueError("use --release to freeze documentation for a stable VERSION")
    status = getattr(args, "status", None)
    if status is not None:
        status = validate_status(status)
        if not args.release:
            raise ValueError("a custom status requires stable release preparation")
    if commit:
        branch = git(root, "branch", "--show-current")
        if not branch:
            raise ValueError("cannot commit documentation on a detached HEAD")
        if git(root, "status", "--porcelain", "--untracked-files=all", "--", *INPUTS):
            raise ValueError("commit documentation inputs first, or run without --commit or --commitpush to preview")
        if push:
            git(root, "remote", "get-url", "--push", "origin")

    api = root / "docs/api"
    for path in (root / "docs", api):
        if path.is_symlink():
            raise ValueError(f"refusing symbolic-link output: {path}")
    existing = snapshots(api)
    # A generated stable snapshot already in Git is immutable, including when
    # local files were edited or removed before this command was invoked.
    for name in git(root, "ls-tree", "-r", "--name-only", "HEAD", "--", "docs/api").splitlines():
        parts = name.split("/")
        if len(parts) == 4 and parts[-1] == "snapshot.json" and VERSION.fullmatch(parts[2]) and "-" not in parts[2]:
            if git(root, "status", "--porcelain", "--untracked-files=all", "--", f"docs/api/{parts[2]}"):
                raise ValueError(f"IronDocs {parts[2]} is frozen and has local changes; restore that snapshot first")
    # Release orchestration can retire its previous beta even when the version jumps.
    previous_prerelease = getattr(args, "retire_prerelease", None) if args.release else None
    retired = [v for v in existing if "-" in v and v != version
               and (not stable or v.split("-", 1)[0] == version or v == previous_prerelease)]
    fingerprint = source_digest(root)
    (root / "docs").mkdir(exist_ok=True)
    with tempfile.TemporaryDirectory(prefix=".irondocs-", dir=root / "docs") as temporary:
        staging = Path(temporary)
        generated = staging / version
        subprocess.run([str(root / "bin/irondoc"), "-quiet", "-d", str(generated),
                        "-sourcepath", str(root / "stdlib/src/main/ironwood"),
                        "-subpackages", "ironwood", "-doctitle", "Ironwood Standard Library",
                        "--doc-version", version], cwd=root, check=True)
        add_package_descriptions(root, generated)
        if source_digest(root) != fingerprint or (root / "VERSION").read_text(encoding="utf-8").strip() != version:
            raise ValueError("source or VERSION changed during generation; rerun the script")
        validate_stdlib_inventory(root, (generated / "README.md").read_text(encoding="utf-8"))
        metadata = {"generator": "IronDocs", "version": version, "source_sha256": fingerprint}
        previous = json.loads(existing.get(version, {}).get("snapshot.json", b"{}"))
        if "status" in previous:
            metadata["status"] = previous["status"]
        if status is not None:
            metadata["status"] = status
        (generated / "snapshot.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
        output = files(generated)
        if stable and version in existing and existing[version] != output:
            raise ValueError(f"IronDocs {version} is frozen; generate the next development version instead")
        versions = {v: contents for v, contents in existing.items() if v not in retired}
        versions[version] = output
        landing = index(versions)
        old_landing = (api / "README.md").read_text(encoding="utf-8") if (api / "README.md").exists() else ""
        changed = existing.get(version) != output or retired or old_landing != landing
        if args.check:
            if changed:
                raise ValueError(f"IronDocs {version} is out of date; run scripts/update-irondocs.sh")
            print(f"IronDocs {version}: generated output is current")
            return
        if changed:
            # Generation and validation finish before any published file is touched.
            api.mkdir(exist_ok=True)
            previous = staging / "previous"
            previous.mkdir()
            moved = []
            installed = False
            try:
                for name in retired + ([version] if version in existing else []):
                    (api / name).rename(previous / name)
                    moved.append(name)
                generated.rename(api / version)
                installed = True
                (staging / "README.md").write_text(landing, encoding="utf-8")
                (staging / "README.md").replace(api / "README.md")
            except OSError:
                if installed:
                    shutil.rmtree(api / version)
                for name in moved:
                    (previous / name).rename(api / name)
                raise
        if not commit:
            print(f"IronDocs {version}: {'generated' if changed else 'unchanged'} (not committed)")
            return
        # Path-limited commits preserve unrelated staged and unstaged user changes.
        git(root, "add", "-A", "--", "docs/api")
        if not git(root, "diff", "--cached", "--name-only", "--", "docs/api"):
            print(f"IronDocs {version}: unchanged; no commit created")
        else:
            git(root, "diff", "--cached", "--check", "--", "docs/api")
            message = f"{'Freeze' if stable else 'Update'} IronDocs for {version}"
            git(root, "commit", "--only", "-m", message, "--", "docs/api")
            print(f"IronDocs {version}: committed {git(root, 'rev-parse', '--short', 'HEAD')}; not pushed")

    if push:
        if git(root, "branch", "--show-current") != branch:
            raise ValueError("current branch changed during generation; no push attempted")
        # Publish only this branch, even when Git is configured to follow tags or mirror refs.
        ref = f"refs/heads/{branch}"
        try:
            git(root, "-c", "remote.origin.mirror=false", "push", "--no-follow-tags", "origin", f"{ref}:{ref}")
        except subprocess.CalledProcessError as error:
            raise ValueError("push failed or its result is uncertain; local commits are preserved. "
                             "Resolve the Git error above, then rerun the same command to retry.") from error
        print(f"IronDocs {version}: pushed {branch} to origin/{branch}")


def main():
    parser = argparse.ArgumentParser(description="Generate standard-library IronDocs using VERSION. No commit or push by default.")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--commit", action="store_true", help="generate and commit only the documentation, without pushing")
    mode.add_argument("--commitpush", action="store_true", help="generate, commit, and push the current branch to origin (no tags)")
    mode.add_argument("--no-commit", action="store_true", help="generate without committing or pushing (the default)")
    mode.add_argument("--check", action="store_true", help="verify generated files without modifying or committing them")
    parser.add_argument("--release", action="store_true", help="freeze a stable VERSION and retire its prerelease snapshot")
    args = parser.parse_args()
    try:
        update(Path(__file__).resolve().parent.parent, args)
    except (OSError, ValueError, subprocess.CalledProcessError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
