#!/usr/bin/env bash
# SPDX-License-Identifier: MIT OR Apache-2.0

set -euo pipefail

IRONWOOD_SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
IRONWOOD_PROJECT_ROOT=$(CDPATH= cd -- "$IRONWOOD_SCRIPT_DIR/.." && pwd)
IRONWOOD_OS=$(uname -s | tr '[:upper:]' '[:lower:]')
IRONWOOD_ARCH=$(uname -m)

case "$IRONWOOD_OS" in
    darwin) IRONWOOD_PLATFORM="macos-$IRONWOOD_ARCH" ;;
    linux) IRONWOOD_PLATFORM="linux-$IRONWOOD_ARCH" ;;
    *)
        echo "error: packaging is supported on macOS and Linux, not $IRONWOOD_OS" >&2
        exit 1
        ;;
esac

IRONWOOD_PACKAGE_NAME="ironwood-$IRONWOOD_PLATFORM"
IRONWOOD_DIST_DIR="$IRONWOOD_PROJECT_ROOT/dist"
IRONWOOD_STAGE_DIR="$IRONWOOD_DIST_DIR/$IRONWOOD_PACKAGE_NAME"

"$IRONWOOD_SCRIPT_DIR/build.sh"
rm -rf "$IRONWOOD_STAGE_DIR"
mkdir -p "$IRONWOOD_STAGE_DIR/bin" "$IRONWOOD_STAGE_DIR/lib" "$IRONWOOD_STAGE_DIR/docs" \
    "$IRONWOOD_STAGE_DIR/examples" "$IRONWOOD_STAGE_DIR/projects" \
    "$IRONWOOD_STAGE_DIR/runtime" "$IRONWOOD_STAGE_DIR/stdlib" \
    "$IRONWOOD_STAGE_DIR/LICENSES"
cp "$IRONWOOD_PROJECT_ROOT/bin/ironwoodc" "$IRONWOOD_STAGE_DIR/bin/ironwoodc"
cp "$IRONWOOD_PROJECT_ROOT/bin/ironjar" "$IRONWOOD_STAGE_DIR/bin/ironjar"
cp "$IRONWOOD_PROJECT_ROOT/compiler/build/ironwoodc.jar" "$IRONWOOD_STAGE_DIR/lib/ironwoodc.jar"
cp "$IRONWOOD_PROJECT_ROOT/compiler/build/ironwood-stdlib.ironjar" \
    "$IRONWOOD_STAGE_DIR/lib/ironwood-stdlib.ironjar"
cp "$IRONWOOD_PROJECT_ROOT/compiler/build/ironwood-testing.ironjar" \
    "$IRONWOOD_STAGE_DIR/lib/ironwood-testing.ironjar"
cp "$IRONWOOD_PROJECT_ROOT/VERSION" "$IRONWOOD_STAGE_DIR/VERSION"
cp "$IRONWOOD_PROJECT_ROOT/README.md" "$IRONWOOD_STAGE_DIR/README.md"
cp "$IRONWOOD_PROJECT_ROOT/LICENSE" "$IRONWOOD_STAGE_DIR/LICENSE"
cp "$IRONWOOD_PROJECT_ROOT/LICENSE-APACHE" "$IRONWOOD_STAGE_DIR/LICENSE-APACHE"
cp "$IRONWOOD_PROJECT_ROOT/LICENSE-MIT" "$IRONWOOD_STAGE_DIR/LICENSE-MIT"
cp "$IRONWOOD_PROJECT_ROOT/docs/LICENSE_MECHANICS" "$IRONWOOD_STAGE_DIR/LICENSE_MECHANICS"
cp "$IRONWOOD_PROJECT_ROOT/LICENSES/GPL-2.0-only.txt" \
    "$IRONWOOD_STAGE_DIR/LICENSES/GPL-2.0-only.txt"
cp "$IRONWOOD_PROJECT_ROOT/LICENSES/Classpath-exception-2.0.txt" \
    "$IRONWOOD_STAGE_DIR/LICENSES/Classpath-exception-2.0.txt"
cp "$IRONWOOD_PROJECT_ROOT/LICENSES/Unicode-15.0.txt" "$IRONWOOD_STAGE_DIR/LICENSES/Unicode-15.0.txt"
cp "$IRONWOOD_PROJECT_ROOT/docs/THIRD_PARTY_NOTICES.md" "$IRONWOOD_STAGE_DIR/THIRD_PARTY_NOTICES.md"
cp "$IRONWOOD_PROJECT_ROOT/docs/COMPILER.md" "$IRONWOOD_STAGE_DIR/docs/COMPILER.md"
cp "$IRONWOOD_PROJECT_ROOT/docs/DECISIONS.md" "$IRONWOOD_STAGE_DIR/docs/DECISIONS.md"
cp "$IRONWOOD_PROJECT_ROOT/docs/LANGUAGE.md" "$IRONWOOD_STAGE_DIR/docs/LANGUAGE.md"
cp "$IRONWOOD_PROJECT_ROOT/docs/MEMORY.md" "$IRONWOOD_STAGE_DIR/docs/MEMORY.md"
cp "$IRONWOOD_PROJECT_ROOT/docs/ROADMAP.md" "$IRONWOOD_STAGE_DIR/docs/ROADMAP.md"
cp "$IRONWOOD_PROJECT_ROOT/docs/STDLIB_ROADMAP.md" "$IRONWOOD_STAGE_DIR/docs/STDLIB_ROADMAP.md"
cp "$IRONWOOD_PROJECT_ROOT/docs/LIBRARY_PORTS.md" "$IRONWOOD_STAGE_DIR/docs/LIBRARY_PORTS.md"
cp "$IRONWOOD_PROJECT_ROOT/docs/OPENJDK_PORTING.md" "$IRONWOOD_STAGE_DIR/docs/OPENJDK_PORTING.md"
cp "$IRONWOOD_PROJECT_ROOT/docs/SOURCE_PROVENANCE.md" "$IRONWOOD_STAGE_DIR/docs/SOURCE_PROVENANCE.md"
cp "$IRONWOOD_PROJECT_ROOT/docs/STDLIB_FLOATING_PARSE_SOURCE_REVIEW.md" "$IRONWOOD_STAGE_DIR/docs/STDLIB_FLOATING_PARSE_SOURCE_REVIEW.md"
cp "$IRONWOOD_PROJECT_ROOT/docs/STDLIB_S0_SOURCE_REVIEW.md" "$IRONWOOD_STAGE_DIR/docs/STDLIB_S0_SOURCE_REVIEW.md"
cp "$IRONWOOD_PROJECT_ROOT/docs/STDLIB_U1_SOURCE_REVIEW.md" "$IRONWOOD_STAGE_DIR/docs/STDLIB_U1_SOURCE_REVIEW.md"
cp "$IRONWOOD_PROJECT_ROOT/docs/STDLIB_U2_SOURCE_REVIEW.md" "$IRONWOOD_STAGE_DIR/docs/STDLIB_U2_SOURCE_REVIEW.md"
cp "$IRONWOOD_PROJECT_ROOT/docs/STDLIB_U3_SOURCE_REVIEW.md" "$IRONWOOD_STAGE_DIR/docs/STDLIB_U3_SOURCE_REVIEW.md"
cp "$IRONWOOD_PROJECT_ROOT/docs/STDLIB_STRING_REVIEW.md" "$IRONWOOD_STAGE_DIR/docs/STDLIB_STRING_REVIEW.md"
mkdir -p "$IRONWOOD_STAGE_DIR/scripts"
cp "$IRONWOOD_PROJECT_ROOT/scripts/GenerateCaseData.java" "$IRONWOOD_STAGE_DIR/scripts/GenerateCaseData.java"
cp "$IRONWOOD_PROJECT_ROOT/docs/SYSTEM_OUTPUT_SOURCE_REVIEW.md" "$IRONWOOD_STAGE_DIR/docs/SYSTEM_OUTPUT_SOURCE_REVIEW.md"
cp "$IRONWOOD_PROJECT_ROOT/docs/TESTING.md" "$IRONWOOD_STAGE_DIR/docs/TESTING.md"
while IFS= read -r IRONWOOD_EXAMPLE_FILE; do
    IRONWOOD_EXAMPLE_RELATIVE=${IRONWOOD_EXAMPLE_FILE#"$IRONWOOD_PROJECT_ROOT/examples/"}
    mkdir -p "$IRONWOOD_STAGE_DIR/examples/$(dirname -- "$IRONWOOD_EXAMPLE_RELATIVE")"
    cp "$IRONWOOD_EXAMPLE_FILE" "$IRONWOOD_STAGE_DIR/examples/$IRONWOOD_EXAMPLE_RELATIVE"
done < <(find "$IRONWOOD_PROJECT_ROOT/examples" -type f \
    \( -name '*.iron' -o -name '*.sh' -o -name 'README.md' \) -print)
while IFS= read -r IRONWOOD_PROJECT_FILE; do
    IRONWOOD_PROJECT_RELATIVE=${IRONWOOD_PROJECT_FILE#"$IRONWOOD_PROJECT_ROOT/projects/"}
    mkdir -p "$IRONWOOD_STAGE_DIR/projects/$(dirname -- "$IRONWOOD_PROJECT_RELATIVE")"
    cp "$IRONWOOD_PROJECT_FILE" "$IRONWOOD_STAGE_DIR/projects/$IRONWOOD_PROJECT_RELATIVE"
done < <(find "$IRONWOOD_PROJECT_ROOT/projects" -type f \
    \( -name '*.iron' -o -name '*.sh' -o -name '*.txt' -o -name 'README.md' \) -print)
cp -R "$IRONWOOD_PROJECT_ROOT/runtime/include" "$IRONWOOD_STAGE_DIR/runtime/include"
cp -R "$IRONWOOD_PROJECT_ROOT/runtime/src" "$IRONWOOD_STAGE_DIR/runtime/src"
cp -R "$IRONWOOD_PROJECT_ROOT/stdlib/src" "$IRONWOOD_STAGE_DIR/stdlib/src"
cp "$IRONWOOD_PROJECT_ROOT/stdlib/README.md" "$IRONWOOD_STAGE_DIR/stdlib/README.md"
cp -R "$IRONWOOD_PROJECT_ROOT/compiler/build/stdlib" "$IRONWOOD_STAGE_DIR/lib/stdlib"

mkdir -p "$IRONWOOD_DIST_DIR"
tar -C "$IRONWOOD_DIST_DIR" -czf "$IRONWOOD_DIST_DIR/$IRONWOOD_PACKAGE_NAME.tar.gz" "$IRONWOOD_PACKAGE_NAME"
echo "packaged $IRONWOOD_DIST_DIR/$IRONWOOD_PACKAGE_NAME.tar.gz"
