#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0

"""Focused lifecycle tests using a tiny standalone Git fixture, not another checkout."""

import argparse
import contextlib
import importlib.util
import io
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest


sys.dont_write_bytecode = True
SPEC = importlib.util.spec_from_file_location("irondocs", Path(__file__).with_name("irondocs.py"))
irondocs = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(irondocs)


class IronDocsWorkflowTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory(prefix="irondocs-git-fixture-")
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name).resolve()
        self.write("VERSION", "0.1.3-beta\n")
        self.source = "stdlib/src/main/ironwood/ironwood/pool/ArrayObjectPool.iron"
        self.write(self.source, "public class ArrayObjectPool {}\n")
        self.write("docs/STDLIB.md", '''# Ironwood standard library

Ironwood currently ships a bundled, Java-shaped standard library from 1
source file. IronDocs covers 1 public and protected type across 1 package:

| Package | Documented types | Purpose |
| --- | ---: | --- |
| `ironwood.pool` | 1 | Object pools |

This document describes the current library.
''')
        self.write("notes.txt", "unrelated notes\n")
        self.write("bin/irondoc", '''#!/usr/bin/env python3
from pathlib import Path
import sys
args = sys.argv[1:]
output = Path(args[args.index("-d") + 1])
version = args[args.index("--doc-version") + 1]
source = Path("stdlib/src/main/ironwood/ironwood/pool/ArrayObjectPool.iron").read_text()
if "BROKEN" in source:
    sys.exit(1)
readme = """<!-- Generated by IronDocs. Do not edit. -->

**API reference** · 1 documented type · 1 package

| Package | Types |
| --- | ---: |
| [`ironwood.pool`](ironwood/pool/package-summary.md) | 1 |
""" + source
for name in ("README.md", "assets/irondocs.svg", "ironwood/pool/ArrayObjectPool.md"):
    path = output / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(readme if name == "README.md" else
                    "<!-- Generated by IronDocs. Do not edit. -->\\n" + version + "\\n" + source)
''')
        (self.root / "bin/irondoc").chmod(0o755)
        self.git("init", "-q", "-b", "fixture")
        self.git("config", "user.name", "IronDocs test")
        self.git("config", "user.email", "irondocs@example.invalid")
        self.git("config", "commit.gpgsign", "false")
        self.git("add", ".")
        self.git("commit", "-qm", "Initial fixture")

    def write(self, name, text):
        path = self.root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)

    def git(self, *args):
        return irondocs.git(self.root, *args)

    def run_update(self, **options):
        values = dict(commit=False, commitpush=False, no_commit=False, check=False, release=False)
        values.update(options)
        with contextlib.redirect_stdout(io.StringIO()) as output:
            irondocs.update(self.root, argparse.Namespace(**values))
        return output.getvalue()

    def commit_input(self, path, value):
        self.write(path, value)
        self.git("add", "--", path)
        self.git("commit", "-qm", "Change input", "--only", "--", path)

    def remote(self):
        temporary = tempfile.TemporaryDirectory(prefix="irondocs-remote-fixture-")
        self.addCleanup(temporary.cleanup)
        remote = Path(temporary.name).resolve()
        irondocs.git(remote, "init", "-q", "--bare")
        irondocs.git(remote, "config", "core.hooksPath", str(remote / "hooks"))
        self.git("remote", "add", "origin", str(remote))
        return remote

    def test_default_generates_without_commit_or_push(self):
        remote = self.remote()
        self.write(self.source, "public class ArrayObjectPool { public int size; }\n")
        revision = self.git("rev-parse", "HEAD")
        self.assertIn("not committed", self.run_update())
        self.assertEqual(revision, self.git("rev-parse", "HEAD"))
        self.assertEqual("", irondocs.git(remote, "for-each-ref"))
        self.assertEqual("", self.git("diff", "--cached", "--name-only"))
        self.assertTrue((self.root / "docs/api/0.1.3-beta/README.md").is_file())
        self.run_update(check=True)

    def test_stdlib_inventory_is_mechanically_checked(self):
        path = self.root / "docs/STDLIB.md"
        original = path.read_text()
        cases = (
            ("from 1\nsource file", "from 2\nsource files",
             "source files: expected 1, found 2"),
            ("covers 1 public", "covers 2 public",
             "documented types: expected 1, found 2"),
            ("`ironwood.pool` | 1", "`ironwood.pool` | 2",
             "package rows differ from generated IronDocs"),
        )
        for old, new, message in cases:
            with self.subTest(message=message):
                path.write_text(original.replace(old, new))
                with self.assertRaisesRegex(ValueError, message):
                    self.run_update()
        path.write_text(original)

    def test_commitpush_scope_and_repeatability(self):
        remote = self.remote()
        self.run_update(commit=True)
        self.assertEqual("", irondocs.git(remote, "for-each-ref"))
        self.commit_input(self.source, "public class ArrayObjectPool { public int size; }\n")
        self.git("branch", "other")
        self.git("-c", "tag.gpgsign=false", "tag", "-a", "v0.1.3", "-m", "Local test tag")
        self.git("config", "push.followTags", "true")
        self.git("config", "remote.origin.mirror", "true")
        self.write("notes.txt", "staged human change\n")
        self.git("add", "notes.txt")
        self.write("notes.txt", "additional unstaged human change\n")
        self.assertIn("pushed fixture to origin/fixture", self.run_update(commitpush=True))
        revision = self.git("rev-parse", "HEAD")
        self.assertEqual(revision, irondocs.git(remote, "rev-parse", "refs/heads/fixture"))
        self.assertEqual("refs/heads/fixture", irondocs.git(remote, "for-each-ref", "--format=%(refname)"))
        changed = self.git("diff-tree", "--no-commit-id", "--name-only", "-r", "HEAD").splitlines()
        self.assertTrue(changed and all(name.startswith("docs/api/") for name in changed))
        self.assertEqual("staged human change", self.git("show", ":notes.txt"))
        self.assertEqual("unrelated notes", irondocs.git(remote, "show", "refs/heads/fixture:notes.txt"))
        self.assertEqual("additional unstaged human change\n", (self.root / "notes.txt").read_text())
        self.assertIn("no commit created", self.run_update(commitpush=True))
        self.assertEqual(revision, self.git("rev-parse", "HEAD"))

    def test_failed_push_preserves_commit_and_can_retry(self):
        remote = self.remote()
        hook = remote / "hooks/pre-receive"
        hook.write_text("#!/bin/sh\nexit 1\n")
        hook.chmod(0o755)
        original = self.git("rev-parse", "HEAD")
        with self.assertRaisesRegex(ValueError, "local commits are preserved"):
            self.run_update(commitpush=True)
        prepared = self.git("rev-parse", "HEAD")
        self.assertNotEqual(original, prepared)
        self.assertEqual("", self.git("status", "--porcelain"))
        self.assertEqual("", irondocs.git(remote, "for-each-ref"))
        hook.unlink()
        self.assertIn("no commit created", self.run_update(commitpush=True))
        self.assertEqual(prepared, self.git("rev-parse", "HEAD"))
        self.assertEqual(prepared, irondocs.git(remote, "rev-parse", "refs/heads/fixture"))

    def test_divergent_remote_is_not_overwritten(self):
        remote = self.remote()
        self.run_update(commitpush=True)
        self.commit_input("notes.txt", "Remote change\n")
        remote_revision = self.git("rev-parse", "HEAD")
        self.git("push", "origin", "refs/heads/fixture:refs/heads/fixture")
        self.git("switch", "-c", "local-work", "HEAD~1")
        self.git("branch", "-D", "fixture")
        self.git("branch", "-m", "fixture")
        self.commit_input(self.source, "public class ArrayObjectPool { public int size; }\n")
        with self.assertRaisesRegex(ValueError, "local commits are preserved"):
            self.run_update(commitpush=True)
        self.assertEqual(remote_revision, irondocs.git(remote, "rev-parse", "refs/heads/fixture"))
        self.assertEqual("Update IronDocs for 0.1.3-beta", self.git("log", "-1", "--format=%s"))
        self.assertEqual("", self.git("status", "--porcelain"))

    def test_cli_modes_and_commit_guards(self):
        self.remote()
        for name in ("irondocs.py", "update-irondocs.sh"):
            self.write(f"scripts/{name}", Path(__file__).with_name(name).read_text())
        script = self.root / "scripts/update-irondocs.sh"
        script.chmod(0o755)
        self.git("add", "scripts")
        self.git("commit", "-qm", "Add documentation command")

        def command(*args):
            return subprocess.run([str(script), *args], cwd=self.root, capture_output=True, text=True)

        original = self.git("rev-parse", "HEAD")
        self.assertEqual(0, command().returncode)
        self.assertEqual(original, self.git("rev-parse", "HEAD"))
        for first, second in (("--commit", "--commitpush"), ("--commitpush", "--check"),
                              ("--commit", "--no-commit")):
            result = command(first, second)
            self.assertEqual(2, result.returncode)
            self.assertIn("not allowed with argument", result.stderr)
        self.assertEqual(original, self.git("rev-parse", "HEAD"))
        self.write(self.source, "public class ArrayObjectPool { public int size; }\n")
        result = command("--commitpush")
        self.assertEqual(1, result.returncode)
        self.assertIn("commit documentation inputs first", result.stderr)
        self.commit_input(self.source, (self.root / self.source).read_text())
        result = command("--commit")
        self.assertEqual(0, result.returncode, result.stderr)
        self.assertIn("not pushed", result.stdout)
        result = command("--commitpush")
        self.assertEqual(0, result.returncode, result.stderr)
        self.assertIn("pushed fixture to origin/fixture", result.stdout)
        self.git("checkout", "--detach")
        result = command("--commitpush")
        self.assertEqual(1, result.returncode)
        self.assertIn("detached HEAD", result.stderr)

    def test_commit_scope_and_repeatability(self):
        self.write("notes.txt", "staged human change\n")
        self.git("add", "notes.txt")
        self.write("notes.txt", "additional unstaged human change\n")
        self.run_update(commit=True)
        self.assertEqual("notes.txt", self.git("diff", "--cached", "--name-only"))
        self.assertEqual("staged human change", self.git("show", ":notes.txt"))
        self.assertEqual("unrelated notes", self.git("show", "HEAD:notes.txt"))
        self.assertEqual("additional unstaged human change\n", (self.root / "notes.txt").read_text())
        changed = self.git("diff-tree", "--no-commit-id", "--name-only", "-r", "HEAD").splitlines()
        self.assertTrue(changed and all(name.startswith("docs/api/") for name in changed))
        revision = self.git("rev-parse", "HEAD")
        self.assertIn("no commit", self.run_update(commit=True))
        self.assertEqual(revision, self.git("rev-parse", "HEAD"))
        self.run_update(check=True)

    def test_release_lifecycle_and_frozen_history(self):
        self.run_update(commit=True)
        self.commit_input("VERSION", "0.1.3\n")
        with self.assertRaisesRegex(ValueError, "use --release"):
            self.run_update(commit=True)
        self.run_update(release=True, commit=True)
        api = self.root / "docs/api"
        self.assertFalse((api / "0.1.3-beta").exists())
        frozen = irondocs.files(api / "0.1.3")
        self.run_update(check=True)
        revision = self.git("rev-parse", "HEAD")
        self.run_update(release=True, commit=True)
        self.assertEqual(revision, self.git("rev-parse", "HEAD"))
        self.commit_input(self.source, "public class ArrayObjectPool { public int size; }\n")
        with self.assertRaisesRegex(ValueError, "frozen"):
            self.run_update(check=True)
        with self.assertRaisesRegex(ValueError, "frozen"):
            self.run_update(release=True, commit=True)
        self.assertEqual(frozen, irondocs.files(api / "0.1.3"))
        self.commit_input("VERSION", "0.1.4-beta\n")
        self.run_update(commit=True)
        self.assertTrue((api / "0.1.4-beta/README.md").is_file())
        self.assertEqual(frozen, irondocs.files(api / "0.1.3"))
        self.assertIn("[0.1.3](0.1.3/README.md)", (api / "README.md").read_text())
        self.run_update(check=True)
        self.write("docs/api/0.1.3/README.md", irondocs.GENERATED + "Changed history\n")
        with self.assertRaisesRegex(ValueError, "frozen and has local changes"):
            self.run_update(commit=True)

    def test_invalid_version_and_release_mode(self):
        with self.assertRaisesRegex(ValueError, "requires a stable VERSION"):
            self.run_update(release=True, commit=True)
        self.write("VERSION", "../../elsewhere\n")
        with self.assertRaisesRegex(ValueError, "invalid VERSION"):
            self.run_update(no_commit=True)
        self.assertFalse((self.root / "docs/api").exists())

    def test_beta_status_is_fixed(self):
        self.assertEqual("| [0.1.3-beta](0.1.3-beta/README.md) | Development (updated in place) |",
                         irondocs.index_row("0.1.3-beta", {"status": "Custom message"}))
        with self.assertRaisesRegex(ValueError, "requires stable release preparation"):
            self.run_update(status="Custom message")
        self.assertFalse((self.root / "docs/api").exists())

    def test_dirty_source_preview_and_stale_page_removal(self):
        self.run_update(commit=True)
        self.write(self.source, "public class ArrayObjectPool { public int size; }\n")
        revision = self.git("rev-parse", "HEAD")
        with self.assertRaisesRegex(ValueError, "commit documentation inputs"):
            self.run_update(commit=True)
        with self.assertRaisesRegex(ValueError, "out of date"):
            self.run_update(check=True)
        self.write("docs/api/0.1.3-beta/stale.md", irondocs.GENERATED + "old type\n")
        self.run_update(no_commit=True)
        self.assertEqual(revision, self.git("rev-parse", "HEAD"))
        self.assertFalse((self.root / "docs/api/0.1.3-beta/stale.md").exists())
        self.git("add", self.source)
        self.git("commit", "-qm", "Commit documented input")
        self.run_update(commit=True)
        self.run_update(check=True)

    def test_failure_preserves_documentation(self):
        self.run_update(commit=True)
        original = irondocs.files(self.root / "docs/api")
        self.commit_input(self.source, "BROKEN\n")
        revision = self.git("rev-parse", "HEAD")
        with self.assertRaises(subprocess.CalledProcessError):
            self.run_update(commit=True)
        self.assertEqual(original, irondocs.files(self.root / "docs/api"))
        self.assertEqual(revision, self.git("rev-parse", "HEAD"))

    def test_unmanaged_files_and_symlinks_are_preserved(self):
        self.run_update(commit=True)
        unknown = self.root / "docs/api/0.1.3-beta/handwritten.md"
        unknown.write_text("Human documentation\n")
        with self.assertRaisesRegex(ValueError, "non-generated"):
            self.run_update(commit=True)
        self.assertEqual("Human documentation\n", unknown.read_text())
        unknown.unlink()
        unknown.symlink_to(self.root / "notes.txt")
        with self.assertRaisesRegex(ValueError, "symbolic-link"):
            self.run_update(commit=True)
        self.assertEqual("unrelated notes\n", (self.root / "notes.txt").read_text())


if __name__ == "__main__":
    unittest.main()
