#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0

"""Exercise release commits, tags, atomic pushes, and CI checks against local Git fixtures."""

import argparse
import contextlib
import io
import json
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch

sys.dont_write_bytecode = True
import irondocs
import release


class ReleaseTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory(prefix="ironwood-release-fixture-")
        self.addCleanup(self.temporary.cleanup)
        self.base = Path(self.temporary.name).resolve()
        self.root = self.base / "project with spaces"
        self.remote = self.base / "origin.git"
        self.root.mkdir()
        self.git("init", "-q", "-b", "main")
        self.git("config", "user.name", "Release test")
        self.git("config", "user.email", "release@example.invalid")
        self.git("config", "commit.gpgsign", "false")
        self.git("config", "tag.gpgsign", "false")
        self.git("config", "core.hooksPath", str(self.base / "no-hooks"))
        self.git("init", "--bare", "-q", str(self.remote))
        self.remote_git("config", "core.hooksPath", str(self.remote / "hooks"))
        self.git("remote", "add", "origin", str(self.remote))
        self.write("VERSION", "0.1.3-beta\n")
        self.write("docs/LANGUAGE_SPECS.md", "Specification for the `0.1.3-beta` source tree.\n")
        self.write("notes.txt", "unrelated source\n")
        self.write("stdlib/src/main/ironwood/ironwood/pool/ArrayObjectPool.iron", "public class ArrayObjectPool {}\n")
        self.write("bin/irondoc", '''#!/usr/bin/env python3
from pathlib import Path
import sys
args = sys.argv[1:]
output = Path(args[args.index("-d") + 1])
version = args[args.index("--doc-version") + 1]
source = Path("stdlib/src/main/ironwood/ironwood/pool/ArrayObjectPool.iron").read_text()
if "BROKEN" in source:
    sys.exit(1)
for name in ("README.md", "assets/irondocs.svg", "ironwood/pool/ArrayObjectPool.md"):
    path = output / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("<!-- Generated by IronDocs. Do not edit. -->\\n" + version + "\\n" + source)
''')
        (self.root / "bin/irondoc").chmod(0o755)
        for name in ("release.sh", "release.py", "irondocs.py"):
            (self.root / "scripts").mkdir(exist_ok=True)
            shutil.copy2(Path(__file__).with_name(name), self.root / "scripts" / name)
        self.git("add", ".")
        self.git("commit", "-qm", "Initial fixture")
        with contextlib.redirect_stdout(io.StringIO()):
            irondocs.update(self.root, argparse.Namespace(commit=True, check=False, release=False))
        self.git("push", "-q", "-u", "origin", "main")
        self.initial = self.git("rev-parse", "HEAD")

    def git(self, *args):
        return subprocess.run(["git", "-C", str(self.root), *args], check=True,
                              stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True).stdout.strip()

    def remote_git(self, *args):
        return self.git("--git-dir", str(self.remote), *args)

    def write(self, name, content):
        path = self.root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    def run_release(self, version="0.1.3", **options):
        values = dict(version=version, dry_run=False, prepare_only=False, resume=False, verify_tag=False)
        values.update(options)
        with contextlib.redirect_stdout(io.StringIO()) as output:
            release.execute(self.root, argparse.Namespace(**values))
        return output.getvalue()

    def assert_unpublished(self):
        self.assertEqual(self.initial, self.remote_git("rev-parse", "refs/heads/main"))
        self.assertEqual("", self.remote_git("tag", "--list", "v0.1.3"))

    def test_release_contains_matching_frozen_api(self):
        output = self.run_release()
        head = self.git("rev-parse", "HEAD")
        stable = self.git("rev-parse", "HEAD^")
        self.assertIn("GitHub will test", output)
        self.assertEqual(head, self.remote_git("rev-parse", "refs/heads/main"))
        self.assertEqual(stable, self.remote_git("rev-parse", "refs/tags/v0.1.3^{commit}"))
        self.assertEqual("tag", self.remote_git("cat-file", "-t", "refs/tags/v0.1.3"))
        self.assertEqual("0.1.3", self.remote_git("show", "v0.1.3:VERSION"))
        self.assertIn("`0.1.3` source tree.", self.remote_git("show", "v0.1.3:docs/LANGUAGE_SPECS.md"))
        self.assertFalse((self.root / "docs/api/0.1.3-beta").exists())
        metadata = json.loads(self.remote_git("show", "v0.1.3:docs/api/0.1.3/snapshot.json"))
        self.assertEqual(irondocs.source_digest(self.root), metadata["source_sha256"])
        self.assertEqual("0.1.3", metadata["version"])
        self.assertEqual("0.1.4-beta", self.remote_git("show", "main:VERSION"))
        self.assertIn("`0.1.4-beta` source tree.", self.remote_git("show", "main:docs/LANGUAGE_SPECS.md"))
        next_metadata = json.loads(self.remote_git("show", "main:docs/api/0.1.4-beta/snapshot.json"))
        self.assertEqual("0.1.4-beta", next_metadata["version"])
        self.assertEqual(metadata["source_sha256"], next_metadata["source_sha256"])
        self.assertEqual(self.git("rev-parse", "v0.1.3:docs/api/0.1.3"),
                         self.git("rev-parse", "HEAD:docs/api/0.1.3"))
        self.assertEqual("", self.git("status", "--porcelain"))
        paths = self.git("diff-tree", "--no-commit-id", "--name-only", "-r", "HEAD").splitlines()
        self.assertTrue(all(p in release.RELEASE_PATHS or p.startswith("docs/api/") for p in paths))
        self.assertEqual("2", self.git("rev-list", "--count", self.initial + "..HEAD"))
        # Execute the same command used by the workflow, including on a detached checkout.
        self.git("checkout", "--detach", "-q", "v0.1.3")
        verified = subprocess.run([str(self.root / "scripts/release.sh"), "0.1.3", "--verify-tag"],
                                  cwd=self.root, capture_output=True, text=True)
        self.assertEqual(0, verified.returncode, verified.stderr)
        self.assertIn("frozen IronDocs", verified.stdout)

    def test_dry_run_preserves_files_commits_and_tags(self):
        original = irondocs.files(self.root / "docs")
        self.assertIn("No files or release refs changed", self.run_release(dry_run=True))
        self.assertIn("IronDocs status: Pool improvements", self.run_release(dry_run=True, status="Pool improvements"))
        self.assertEqual(original, irondocs.files(self.root / "docs"))
        self.assertEqual(self.initial, self.git("rev-parse", "HEAD"))
        self.assertEqual("", self.git("tag", "--list"))
        self.assert_unpublished()

    def test_custom_status_cli_resume_and_tag_verification(self):
        message = 'Pool | *fixes* <fast> & "Unicode: ação" [notes] `code`'
        row = '| [0.1.3](0.1.3/README.md) | Pool \\| \\*fixes\\* &lt;fast&gt; &amp; "Unicode: ação" \\[notes\\] \\`code\\` |'
        command = [str(self.root / "scripts/release.sh"), "0.1.3"]
        result = subprocess.run([*command, "--status", message, "--prepare-only"],
                                cwd=self.root, capture_output=True, text=True)
        self.assertEqual(0, result.returncode, result.stderr)
        self.assert_unpublished()
        prepared = self.git("rev-parse", "HEAD")
        metadata = json.loads(self.git("show", "v0.1.3:docs/api/0.1.3/snapshot.json"))
        self.assertEqual(message, metadata["status"])
        self.assertIn(row, self.git("show", "v0.1.3:docs/api/README.md").splitlines())
        self.assertIn(row, (self.root / "docs/api/README.md").read_text().splitlines())
        with self.assertRaisesRegex(ValueError, "differs from the prepared release"):
            self.run_release(resume=True, status="Different message")
        self.assertEqual(prepared, self.git("rev-parse", "HEAD"))
        self.assert_unpublished()
        self.run_release(resume=True)
        self.assertIn("already pushed", self.run_release(resume=True, status=message))
        self.assertEqual(prepared, self.remote_git("rev-parse", "main"))
        self.git("checkout", "--detach", "-q", "v0.1.3")
        self.run_release(verify_tag=True, status=message)
        with self.assertRaisesRegex(ValueError, "differs from the prepared release"):
            self.run_release(verify_tag=True, status="Different message")
        with contextlib.redirect_stdout(io.StringIO()):
            irondocs.update(self.root, argparse.Namespace(check=True, release=False))
        self.assertEqual("", self.git("status", "--porcelain"))

    def test_invalid_status_fails_before_preparation(self):
        for status in ("", "   ", "First\nSecond", "Trailing\n", "First\rSecond", "Nul\0text"):
            with self.subTest(status=status), patch.object(release, "remote_state") as remote_state:
                with self.assertRaisesRegex(ValueError, "non-empty, single-line"):
                    self.run_release(status=status)
                remote_state.assert_not_called()
        missing = subprocess.run([str(self.root / "scripts/release.sh"), "0.1.3", "--status"],
                                 cwd=self.root, capture_output=True, text=True)
        self.assertEqual(2, missing.returncode)
        self.assertEqual(self.initial, self.git("rev-parse", "HEAD"))
        self.assertEqual("", self.git("status", "--porcelain"))
        self.assert_unpublished()

    def test_requires_main_and_clean_index_and_worktree(self):
        self.git("checkout", "-qb", "feature")
        with self.assertRaisesRegex(ValueError, "main branch"):
            self.run_release()
        self.git("checkout", "-q", "main")
        for name, staged in (("untracked.txt", False), ("notes.txt", False), ("notes.txt", True)):
            with self.subTest(name=name, staged=staged):
                self.write(name, "human change\n")
                if staged:
                    self.git("add", name)
                with self.assertRaisesRegex(ValueError, "clean working tree"):
                    self.run_release()
                self.assertEqual("human change\n", (self.root / name).read_text())
                if name == "untracked.txt":
                    (self.root / name).unlink()
                else:
                    self.git("restore", "--staged", "--worktree", name)
        self.assert_unpublished()

    def test_requires_synchronized_main(self):
        self.write("notes.txt", "local commit\n")
        self.git("commit", "-qam", "Unpushed change")
        with self.assertRaisesRegex(ValueError, "synchronized"):
            self.run_release()
        self.assertEqual("0.1.3-beta", (self.root / "VERSION").read_text().strip())
        self.assert_unpublished()

    def test_version_and_tag_guards(self):
        for version in ("v0.1.3", "0.1.3-beta", "../../elsewhere", "0.1.4"):
            with self.subTest(version=version), self.assertRaises(ValueError):
                self.run_release(version)
        self.git("tag", "v0.1.3")
        with self.assertRaisesRegex(ValueError, "already exists"):
            self.run_release()
        self.git("tag", "-d", "v0.1.3")
        self.remote_git("tag", "v0.1.3", "refs/heads/main")
        with self.assertRaisesRegex(ValueError, "already exists"):
            self.run_release()
        self.assertEqual(self.initial, self.git("rev-parse", "HEAD"))

    def test_prepare_resume_and_idempotent_retry(self):
        self.run_release(prepare_only=True)
        self.assert_unpublished()
        prepared = self.git("rev-parse", "HEAD")
        stable = self.git("rev-parse", "v0.1.3^{commit}")
        self.git("checkout", "--detach", "-q", "v0.1.3")
        with self.assertRaisesRegex(ValueError, "belong to origin/main"):
            self.run_release(verify_tag=True)
        self.git("checkout", "-q", "main")
        # Reconstruct a missing local tag from the verified stable parent.
        self.git("tag", "-d", "v0.1.3")
        self.run_release(resume=True)
        self.assertIn("already pushed", self.run_release(resume=True))
        self.assertEqual(prepared, self.git("rev-parse", "HEAD"))
        self.assertEqual(stable, self.remote_git("rev-parse", "refs/tags/v0.1.3^{commit}"))

    def test_resume_refuses_to_move_an_existing_tag(self):
        self.run_release(prepare_only=True)
        tag = self.git("rev-parse", "refs/tags/v0.1.3")
        self.write("notes.txt", "changed after tagging\n")
        self.git("commit", "-qam", "Later local change")
        with self.assertRaisesRegex(ValueError, "directly follow"):
            self.run_release(resume=True)
        self.assertEqual(tag, self.git("rev-parse", "refs/tags/v0.1.3"))
        self.assert_unpublished()

    def test_failed_push_is_atomic_and_resumable(self):
        hook = self.remote / "hooks/pre-receive"
        hook.write_text("#!/bin/sh\nexit 1\n")
        hook.chmod(0o755)
        with self.assertRaisesRegex(ValueError, "--resume"):
            self.run_release()
        self.assert_unpublished()
        prepared = self.git("rev-parse", "HEAD")
        self.assertEqual(self.git("rev-parse", prepared + "^"), self.git("rev-parse", "v0.1.3^{commit}"))
        hook.unlink()
        self.run_release(resume=True)
        self.assertEqual(prepared, self.remote_git("rev-parse", "refs/heads/main"))

    def test_concurrent_main_push_does_not_publish_tag(self):
        original_push = release.push_release

        def race(root, version):
            tree = self.git("rev-parse", self.initial + "^{tree}")
            other = self.git("commit-tree", tree, "-p", self.initial, "-m", "Concurrent main change")
            self.git("push", "-q", "origin", other + ":refs/heads/main")
            original_push(root, version)

        with patch.object(release, "push_release", race), self.assertRaisesRegex(ValueError, "--resume"):
            self.run_release()
        self.assertEqual("", self.remote_git("tag", "--list", "v0.1.3"))
        with self.assertRaisesRegex(ValueError, "diverged"):
            self.run_release(resume=True)

    def test_generation_failure_never_publishes(self):
        self.write("stdlib/src/main/ironwood/ironwood/pool/ArrayObjectPool.iron", "BROKEN\n")
        self.git("add", ".")
        self.git("commit", "-qm", "Invalid documentation input")
        self.git("push", "-q", "origin", "main")
        self.initial = self.git("rev-parse", "HEAD")
        original = irondocs.files(self.root / "docs/api")
        with self.assertRaisesRegex(ValueError, "preparation failed"):
            self.run_release()
        self.assertEqual(original, irondocs.files(self.root / "docs/api"))
        self.assertEqual(self.initial, self.git("rev-parse", "HEAD"))
        self.assertEqual("", self.git("tag", "--list"))
        self.assert_unpublished()

    def test_missing_or_stale_frozen_api_is_rejected(self):
        self.run_release(prepare_only=True)
        release.verify_snapshot(self.root, "0.1.3")
        landing = self.root / "docs/api/README.md"
        original_landing = landing.read_text()
        landing.write_text(original_landing.replace("Stable release", "Unexpected status"))
        with self.assertRaisesRegex(ValueError, "index must match"):
            release.verify_snapshot(self.root, "0.1.3")
        landing.write_text(original_landing)
        path = self.root / "docs/api/0.1.3/snapshot.json"
        original = path.read_text()
        metadata = json.loads(original)
        metadata["source_sha256"] = "stale"
        path.write_text(json.dumps(metadata))
        with self.assertRaisesRegex(ValueError, "fingerprint"):
            release.verify_snapshot(self.root, "0.1.3")
        path.write_text(original)
        (self.root / "docs/api/0.1.3/README.md").unlink()
        with self.assertRaisesRegex(ValueError, "incomplete"):
            release.verify_snapshot(self.root, "0.1.3")
        self.assert_unpublished()

    def test_resume_after_stable_commit_before_tag_and_beta(self):
        with patch.object(release, "prepare_development", side_effect=ValueError("Interrupted preparation")):
            with self.assertRaisesRegex(ValueError, "--resume"):
                self.run_release()
        stable = self.git("rev-parse", "HEAD")
        self.assertEqual("0.1.3", (self.root / "VERSION").read_text().strip())
        self.assert_unpublished()
        self.git("tag", "-d", "v0.1.3")
        self.run_release(resume=True)
        self.assertEqual(stable, self.remote_git("rev-parse", "v0.1.3^{commit}"))
        self.assertEqual("0.1.4-beta", self.remote_git("show", "main:VERSION"))

    def test_beta_generation_failure_does_not_publish_release(self):
        original = irondocs.update

        def fail_beta(root, args):
            if not args.release:
                raise ValueError("Beta generation failed")
            return original(root, args)

        with patch.object(irondocs, "update", side_effect=fail_beta):
            with self.assertRaisesRegex(ValueError, "--resume"):
                self.run_release()
        stable = self.git("rev-parse", "v0.1.3^{commit}")
        self.assertEqual(stable, self.git("rev-parse", "HEAD"))
        self.assert_unpublished()
        with self.assertRaisesRegex(ValueError, "clean working tree"):
            self.run_release(resume=True)
        # Only the temporary fixture's uncommitted version changes are restored.
        self.git("restore", "VERSION", "docs/LANGUAGE_SPECS.md")
        self.run_release(resume=True)
        self.assertEqual(stable, self.remote_git("rev-parse", "v0.1.3^{commit}"))
        self.assertEqual("0.1.4-beta", self.remote_git("show", "main:VERSION"))

    def test_resume_rejects_beta_changes_to_a_stable_snapshot(self):
        self.run_release(prepare_only=True)
        tag = self.git("rev-parse", "v0.1.3")
        self.write("docs/api/0.1.3/README.md", irondocs.GENERATED + "Changed stable reference\n")
        self.git("commit", "-qam", "Amended beta", "--amend")
        with self.assertRaisesRegex(ValueError, "unexpected changes"):
            self.run_release(resume=True)
        self.assertEqual(tag, self.git("rev-parse", "v0.1.3"))
        self.assert_unpublished()

    def test_resume_rejects_a_tag_on_the_beta_commit(self):
        self.run_release(prepare_only=True)
        self.git("tag", "-f", "v0.1.3", "HEAD")
        wrong_tag = self.git("rev-parse", "v0.1.3")
        with self.assertRaisesRegex(ValueError, "different commit"):
            self.run_release(resume=True)
        self.assertEqual(wrong_tag, self.git("rev-parse", "v0.1.3"))
        self.assert_unpublished()

    def test_next_release_preserves_history_and_publishes_only_requested_refs(self):
        self.git("tag", "-a", "unrelated-local-tag", "-m", "Keep local")
        self.git("branch", "unrelated-local-branch")
        self.git("config", "push.followTags", "true")
        self.git("config", "remote.origin.mirror", "true")
        self.run_release(status="Pool improvements")
        frozen = self.git("rev-parse", "v0.1.3:docs/api/0.1.3")
        old_tag = self.git("rev-parse", "v0.1.3")
        self.assertEqual("refs/heads/main\nrefs/tags/v0.1.3",
                         self.remote_git("for-each-ref", "--format=%(refname)"))
        # Ordinary IronDocs updates now target the automatically created beta.
        self.write("stdlib/src/main/ironwood/ironwood/pool/ArrayObjectPool.iron",
                   "public class ArrayObjectPool { public int size; }\n")
        self.git("commit", "-qam", "Next development source")
        with contextlib.redirect_stdout(io.StringIO()):
            irondocs.update(self.root, argparse.Namespace(commitpush=True, check=False, release=False))
        self.assertEqual(frozen, self.git("rev-parse", "HEAD:docs/api/0.1.3"))
        with contextlib.redirect_stdout(io.StringIO()):
            irondocs.update(self.root, argparse.Namespace(check=True, release=False))
        self.assertIn("| [0.1.3](0.1.3/README.md) | Pool improvements |",
                      (self.root / "docs/api/README.md").read_text())
        self.run_release("0.1.4")
        self.assertEqual("0.1.5-beta", self.remote_git("show", "main:VERSION"))
        self.assertEqual("0.1.4", self.remote_git("show", "v0.1.4:VERSION"))
        self.assertEqual(old_tag, self.remote_git("rev-parse", "v0.1.3"))
        self.assertEqual(frozen, self.remote_git("rev-parse", "main:docs/api/0.1.3"))
        self.assertFalse((self.root / "docs/api/0.1.4-beta").exists())
        self.assertTrue((self.root / "docs/api/0.1.5-beta").exists())
        landing = self.remote_git("show", "main:docs/api/README.md")
        self.assertIn("| [0.1.3](0.1.3/README.md) | Pool improvements |", landing)
        self.assertIn("| [0.1.4](0.1.4/README.md) | Stable release |", landing)
        self.assertIn("| [0.1.5-beta](0.1.5-beta/README.md) | Development (updated in place) |", landing)
        metadata = json.loads(self.remote_git("show", "main:docs/api/0.1.5-beta/snapshot.json"))
        self.assertNotIn("status", metadata)


if __name__ == "__main__":
    unittest.main()
