# SPDX-License-Identifier: MIT OR Apache-2.0
# Source pins shared by preparation, validation and distribution inventories.
format=1
openssl.version=3.5.8
openssl.url=https://github.com/openssl/openssl/releases/download/openssl-3.5.8/openssl-3.5.8.tar.gz
openssl.sha256=a8f84a39918ec6415ce765d9b429d313ba97b8143169c172e734b9514464f5b2
openssl.license=Apache-2.0
ca.version=2026-08-13
ca.url=https://curl.se/ca/cacert-2026-08-13.pem
ca.sha256=f66dff1bdf8f96060b8177976f8b7d9254bc89bc4db933d769f7384d28480bc9
ca.license=MPL-2.0
llvm.version=23.1.0
perl.version=v5.32.1
make.version=GNU Make 4.4.1
python.version=3.14
configuration=no-shared no-module no-dso no-autoload-config no-legacy no-engine no-comp no-zlib no-zstd no-brotli no-quic no-tests no-apps no-docs no-threads no-pinshared
linux.glibc=2.17
macos.deployment=11.0
